package com.bibisco.dao.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bibisco.dao.model.Characters;
import com.bibisco.dao.model.CharactersExample;
import com.bibisco.dao.model.CharactersWithBLOBs;

public interface CharactersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int countByExample(CharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int deleteByExample(CharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int deleteByPrimaryKey(Long idCharacter);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int insert(CharactersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int insertSelective(CharactersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	List<CharactersWithBLOBs> selectByExampleWithBLOBs(CharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	List<Characters> selectByExample(CharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	CharactersWithBLOBs selectByPrimaryKey(Long idCharacter);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int updateByExampleSelective(@Param("record") CharactersWithBLOBs record, @Param("example") CharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") CharactersWithBLOBs record, @Param("example") CharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int updateByExample(@Param("record") Characters record, @Param("example") CharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int updateByPrimaryKeySelective(CharactersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(CharactersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	int updateByPrimaryKey(Characters record);

	int shiftUp( @Param("startPosition")Integer startPosition, @Param("endPosition")Integer endPosition, @Param("mainCharacter")String mainCharacter);
	
	int shiftDown(@Param("startPosition")Integer startPosition, @Param("endPosition")Integer endPosition, @Param("mainCharacter")String mainCharacter);
}