package com.bibisco.dao.client;

import com.bibisco.dao.model.Chapters;
import com.bibisco.dao.model.ChaptersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.bibisco.dao.model.ChaptersWithBLOBs;

public interface ChaptersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int countByExample(ChaptersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int deleteByExample(ChaptersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int deleteByPrimaryKey(Long idChapter);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int insert(ChaptersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int insertSelective(ChaptersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	List<ChaptersWithBLOBs> selectByExampleWithBLOBs(ChaptersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	List<Chapters> selectByExample(ChaptersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	ChaptersWithBLOBs selectByPrimaryKey(Long idChapter);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int updateByExampleSelective(@Param("record") ChaptersWithBLOBs record, @Param("example") ChaptersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") ChaptersWithBLOBs record, @Param("example") ChaptersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int updateByExample(@Param("record") Chapters record, @Param("example") ChaptersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int updateByPrimaryKeySelective(ChaptersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(ChaptersWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHAPTERS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	int updateByPrimaryKey(Chapters record);
	
	int shiftUp( @Param("startPosition")Integer startPosition, @Param("endPosition")Integer endPosition);
	
	int shiftDown(@Param("startPosition")Integer startPosition, @Param("endPosition")Integer endPosition);
	
	void deleteByPosition(Integer position);
}