package com.bibisco.dao.client;

import com.bibisco.dao.model.Images;
import com.bibisco.dao.model.ImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int countByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int deleteByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int deleteByPrimaryKey(Long idImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int insertSelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    List<Images> selectByExampleWithBLOBs(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    List<Images> selectByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    Images selectByPrimaryKey(Long idImage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int updateByExampleSelective(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int updateByExample(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int updateByPrimaryKeySelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int updateByPrimaryKeyWithBLOBs(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.IMAGES
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    int updateByPrimaryKey(Images record);
}