package com.bibisco.dao.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bibisco.dao.model.Properties;
import com.bibisco.dao.model.PropertiesExample;

public interface PropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int countByExample(PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int deleteByExample(PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int deleteByPrimaryKey(String property);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int insert(Properties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int insertSelective(Properties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    List<Properties> selectByExample(PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    Properties selectByPrimaryKey(String property);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int updateByExampleSelective(@Param("record") Properties record, @Param("example") PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int updateByExample(@Param("record") Properties record, @Param("example") PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int updateByPrimaryKeySelective(Properties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROPERTIES
     *
     * @mbggenerated Sat Aug 03 09:51:33 CEST 2013
     */
    int updateByPrimaryKey(Properties record);
}