package com.bibisco.dao.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bibisco.dao.model.SceneRevisionCharactersExample;
import com.bibisco.dao.model.SceneRevisionCharactersKey;

public interface SceneRevisionCharactersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	int countByExample(SceneRevisionCharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	int deleteByExample(SceneRevisionCharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	int deleteByPrimaryKey(SceneRevisionCharactersKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	int insert(SceneRevisionCharactersKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	int insertSelective(SceneRevisionCharactersKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	List<SceneRevisionCharactersKey> selectByExample(SceneRevisionCharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	int updateByExampleSelective(@Param("record") SceneRevisionCharactersKey record, @Param("example") SceneRevisionCharactersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISION_CHARACTERS
	 * @mbggenerated  Wed Jul 24 20:58:05 CEST 2013
	 */
	int updateByExample(@Param("record") SceneRevisionCharactersKey record, @Param("example") SceneRevisionCharactersExample example);
}