package com.bibisco.dao.client;

import com.bibisco.dao.model.SceneRevisions;
import com.bibisco.dao.model.SceneRevisionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SceneRevisionsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int countByExample(SceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int deleteByExample(SceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int deleteByPrimaryKey(Long idSceneRevision);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int insert(SceneRevisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int insertSelective(SceneRevisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	List<SceneRevisions> selectByExampleWithBLOBs(SceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	List<SceneRevisions> selectByExample(SceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	SceneRevisions selectByPrimaryKey(Long idSceneRevision);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int updateByExampleSelective(@Param("record") SceneRevisions record, @Param("example") SceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") SceneRevisions record, @Param("example") SceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int updateByExample(@Param("record") SceneRevisions record, @Param("example") SceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int updateByPrimaryKeySelective(SceneRevisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(SceneRevisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	int updateByPrimaryKey(SceneRevisions record);

	void deleteByChapterPosition(Integer chapterPosition);
	
	void deleteBySceneSelection(Integer idScene);
	
	SceneRevisions selectNextRevisionNumber(Integer idScene);
	
	SceneRevisions getSelectedByIdScene(Integer idScene);
	
	void shiftDown(Integer revisionNumber);
}