package com.bibisco.dao.client;

import com.bibisco.dao.model.Scenes;
import com.bibisco.dao.model.ScenesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScenesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int countByExample(ScenesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int deleteByExample(ScenesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int deleteByPrimaryKey(Long idScene);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int insert(Scenes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int insertSelective(Scenes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	List<Scenes> selectByExample(ScenesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	Scenes selectByPrimaryKey(Long idScene);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int updateByExampleSelective(@Param("record") Scenes record, @Param("example") ScenesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int updateByExample(@Param("record") Scenes record, @Param("example") ScenesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int updateByPrimaryKeySelective(Scenes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENES
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	int updateByPrimaryKey(Scenes record);

	int shiftUp( @Param("startPosition")Integer startPosition, @Param("endPosition")Integer endPosition);
	
	int shiftDown(@Param("startPosition")Integer startPosition, @Param("endPosition")Integer endPosition);
	
	void deleteByChapterPosition(Integer chapterPosition);
}