package com.bibisco.dao.client;

import com.bibisco.dao.model.VCharacterOccurences;
import com.bibisco.dao.model.VCharacterOccurencesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VCharacterOccurencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_CHARACTER_OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    int countByExample(VCharacterOccurencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_CHARACTER_OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    int deleteByExample(VCharacterOccurencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_CHARACTER_OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    int insert(VCharacterOccurences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_CHARACTER_OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    int insertSelective(VCharacterOccurences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_CHARACTER_OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    List<VCharacterOccurences> selectByExample(VCharacterOccurencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_CHARACTER_OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    int updateByExampleSelective(@Param("record") VCharacterOccurences record, @Param("example") VCharacterOccurencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_CHARACTER_OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    int updateByExample(@Param("record") VCharacterOccurences record, @Param("example") VCharacterOccurencesExample example);
}