package com.bibisco.dao.client;

import com.bibisco.dao.model.VSelectedSceneRevisions;
import com.bibisco.dao.model.VSelectedSceneRevisionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VSelectedSceneRevisionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    int countByExample(VSelectedSceneRevisionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    int deleteByExample(VSelectedSceneRevisionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    int insert(VSelectedSceneRevisions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    int insertSelective(VSelectedSceneRevisions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    List<VSelectedSceneRevisions> selectByExampleWithBLOBs(VSelectedSceneRevisionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    List<VSelectedSceneRevisions> selectByExample(VSelectedSceneRevisionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    int updateByExampleSelective(@Param("record") VSelectedSceneRevisions record, @Param("example") VSelectedSceneRevisionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") VSelectedSceneRevisions record, @Param("example") VSelectedSceneRevisionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    int updateByExample(@Param("record") VSelectedSceneRevisions record, @Param("example") VSelectedSceneRevisionsExample example);
}