package com.bibisco.dao.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bibisco.dao.model.VSelectedSceneRevisions;
import com.bibisco.dao.model.VSelectedSceneRevisionsExample;

public interface VSelectedSceneRevisionsMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	int countByExample(VSelectedSceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	int deleteByExample(VSelectedSceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	int insert(VSelectedSceneRevisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	int insertSelective(VSelectedSceneRevisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	List<VSelectedSceneRevisions> selectByExampleWithBLOBs(VSelectedSceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	List<VSelectedSceneRevisions> selectByExample(VSelectedSceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") VSelectedSceneRevisions record, @Param("example") VSelectedSceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") VSelectedSceneRevisions record, @Param("example") VSelectedSceneRevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	int updateByExample(@Param("record") VSelectedSceneRevisions record, @Param("example") VSelectedSceneRevisionsExample example);

	List<VSelectedSceneRevisions> selectChapterScenesByIdScene(Integer idScene);
}