package com.bibisco.dao.model;

public class CharacterInfos extends CharacterInfosKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTER_INFOS.INFO
	 * @mbggenerated  Thu Jun 27 00:11:42 CEST 2013
	 */
	private String info;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTER_INFOS.INFO
	 * @return  the value of PUBLIC.CHARACTER_INFOS.INFO
	 * @mbggenerated  Thu Jun 27 00:11:42 CEST 2013
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTER_INFOS.INFO
	 * @param info  the value for PUBLIC.CHARACTER_INFOS.INFO
	 * @mbggenerated  Thu Jun 27 00:11:42 CEST 2013
	 */
	public void setInfo(String info) {
		this.info = info;
	}
}