package com.bibisco.dao.model;

public class Characters {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.ID_CHARACTER
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Long idCharacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.MAIN_CHARACTER
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String mainCharacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.NAME
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.POSITION
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PERSONAL_DATA_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer personalDataTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PERSONAL_DATA_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String personalDataInterview;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PHYSIONOMY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer physionomyTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PHYSIONOMY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String physionomyInterview;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PSYCHOLOGY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer psychologyTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PSYCHOLOGY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String psychologyInterview;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.BEHAVIORS_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer behaviorsTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.BEHAVIORS_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String behaviorsInterview;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.SOCIOLOGY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer sociologyTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.SOCIOLOGY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String sociologyInterview;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.IDEAS_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer ideasTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.IDEAS_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String ideasInterview;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer lifebeforestorybeginningTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.CONFLICT_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer conflictTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer evolutionduringthestoryTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private Integer secondaryCharacterDescriptionTaskStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.ID_CHARACTER
	 * @return  the value of PUBLIC.CHARACTERS.ID_CHARACTER
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Long getIdCharacter() {
		return idCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.ID_CHARACTER
	 * @param idCharacter  the value for PUBLIC.CHARACTERS.ID_CHARACTER
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setIdCharacter(Long idCharacter) {
		this.idCharacter = idCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.MAIN_CHARACTER
	 * @return  the value of PUBLIC.CHARACTERS.MAIN_CHARACTER
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getMainCharacter() {
		return mainCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.MAIN_CHARACTER
	 * @param mainCharacter  the value for PUBLIC.CHARACTERS.MAIN_CHARACTER
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setMainCharacter(String mainCharacter) {
		this.mainCharacter = mainCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.NAME
	 * @return  the value of PUBLIC.CHARACTERS.NAME
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.NAME
	 * @param name  the value for PUBLIC.CHARACTERS.NAME
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.POSITION
	 * @return  the value of PUBLIC.CHARACTERS.POSITION
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.POSITION
	 * @param position  the value for PUBLIC.CHARACTERS.POSITION
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PERSONAL_DATA_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.PERSONAL_DATA_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getPersonalDataTaskStatus() {
		return personalDataTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PERSONAL_DATA_TASK_STATUS
	 * @param personalDataTaskStatus  the value for PUBLIC.CHARACTERS.PERSONAL_DATA_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPersonalDataTaskStatus(Integer personalDataTaskStatus) {
		this.personalDataTaskStatus = personalDataTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PERSONAL_DATA_INTERVIEW
	 * @return  the value of PUBLIC.CHARACTERS.PERSONAL_DATA_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getPersonalDataInterview() {
		return personalDataInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PERSONAL_DATA_INTERVIEW
	 * @param personalDataInterview  the value for PUBLIC.CHARACTERS.PERSONAL_DATA_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPersonalDataInterview(String personalDataInterview) {
		this.personalDataInterview = personalDataInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PHYSIONOMY_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.PHYSIONOMY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getPhysionomyTaskStatus() {
		return physionomyTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PHYSIONOMY_TASK_STATUS
	 * @param physionomyTaskStatus  the value for PUBLIC.CHARACTERS.PHYSIONOMY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPhysionomyTaskStatus(Integer physionomyTaskStatus) {
		this.physionomyTaskStatus = physionomyTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PHYSIONOMY_INTERVIEW
	 * @return  the value of PUBLIC.CHARACTERS.PHYSIONOMY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getPhysionomyInterview() {
		return physionomyInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PHYSIONOMY_INTERVIEW
	 * @param physionomyInterview  the value for PUBLIC.CHARACTERS.PHYSIONOMY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPhysionomyInterview(String physionomyInterview) {
		this.physionomyInterview = physionomyInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PSYCHOLOGY_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.PSYCHOLOGY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getPsychologyTaskStatus() {
		return psychologyTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PSYCHOLOGY_TASK_STATUS
	 * @param psychologyTaskStatus  the value for PUBLIC.CHARACTERS.PSYCHOLOGY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPsychologyTaskStatus(Integer psychologyTaskStatus) {
		this.psychologyTaskStatus = psychologyTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PSYCHOLOGY_INTERVIEW
	 * @return  the value of PUBLIC.CHARACTERS.PSYCHOLOGY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getPsychologyInterview() {
		return psychologyInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PSYCHOLOGY_INTERVIEW
	 * @param psychologyInterview  the value for PUBLIC.CHARACTERS.PSYCHOLOGY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPsychologyInterview(String psychologyInterview) {
		this.psychologyInterview = psychologyInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.BEHAVIORS_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.BEHAVIORS_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getBehaviorsTaskStatus() {
		return behaviorsTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.BEHAVIORS_TASK_STATUS
	 * @param behaviorsTaskStatus  the value for PUBLIC.CHARACTERS.BEHAVIORS_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setBehaviorsTaskStatus(Integer behaviorsTaskStatus) {
		this.behaviorsTaskStatus = behaviorsTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.BEHAVIORS_INTERVIEW
	 * @return  the value of PUBLIC.CHARACTERS.BEHAVIORS_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getBehaviorsInterview() {
		return behaviorsInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.BEHAVIORS_INTERVIEW
	 * @param behaviorsInterview  the value for PUBLIC.CHARACTERS.BEHAVIORS_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setBehaviorsInterview(String behaviorsInterview) {
		this.behaviorsInterview = behaviorsInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.SOCIOLOGY_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.SOCIOLOGY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getSociologyTaskStatus() {
		return sociologyTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.SOCIOLOGY_TASK_STATUS
	 * @param sociologyTaskStatus  the value for PUBLIC.CHARACTERS.SOCIOLOGY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setSociologyTaskStatus(Integer sociologyTaskStatus) {
		this.sociologyTaskStatus = sociologyTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.SOCIOLOGY_INTERVIEW
	 * @return  the value of PUBLIC.CHARACTERS.SOCIOLOGY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getSociologyInterview() {
		return sociologyInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.SOCIOLOGY_INTERVIEW
	 * @param sociologyInterview  the value for PUBLIC.CHARACTERS.SOCIOLOGY_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setSociologyInterview(String sociologyInterview) {
		this.sociologyInterview = sociologyInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.IDEAS_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.IDEAS_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getIdeasTaskStatus() {
		return ideasTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.IDEAS_TASK_STATUS
	 * @param ideasTaskStatus  the value for PUBLIC.CHARACTERS.IDEAS_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setIdeasTaskStatus(Integer ideasTaskStatus) {
		this.ideasTaskStatus = ideasTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.IDEAS_INTERVIEW
	 * @return  the value of PUBLIC.CHARACTERS.IDEAS_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getIdeasInterview() {
		return ideasInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.IDEAS_INTERVIEW
	 * @param ideasInterview  the value for PUBLIC.CHARACTERS.IDEAS_INTERVIEW
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setIdeasInterview(String ideasInterview) {
		this.ideasInterview = ideasInterview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getLifebeforestorybeginningTaskStatus() {
		return lifebeforestorybeginningTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING_TASK_STATUS
	 * @param lifebeforestorybeginningTaskStatus  the value for PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setLifebeforestorybeginningTaskStatus(Integer lifebeforestorybeginningTaskStatus) {
		this.lifebeforestorybeginningTaskStatus = lifebeforestorybeginningTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.CONFLICT_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.CONFLICT_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getConflictTaskStatus() {
		return conflictTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.CONFLICT_TASK_STATUS
	 * @param conflictTaskStatus  the value for PUBLIC.CHARACTERS.CONFLICT_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setConflictTaskStatus(Integer conflictTaskStatus) {
		this.conflictTaskStatus = conflictTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getEvolutionduringthestoryTaskStatus() {
		return evolutionduringthestoryTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY_TASK_STATUS
	 * @param evolutionduringthestoryTaskStatus  the value for PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setEvolutionduringthestoryTaskStatus(Integer evolutionduringthestoryTaskStatus) {
		this.evolutionduringthestoryTaskStatus = evolutionduringthestoryTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS
	 * @return  the value of PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Integer getSecondaryCharacterDescriptionTaskStatus() {
		return secondaryCharacterDescriptionTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS
	 * @param secondaryCharacterDescriptionTaskStatus  the value for PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setSecondaryCharacterDescriptionTaskStatus(Integer secondaryCharacterDescriptionTaskStatus) {
		this.secondaryCharacterDescriptionTaskStatus = secondaryCharacterDescriptionTaskStatus;
	}
}