package com.bibisco.dao.model;

public class Images {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGES.ID_IMAGE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    private Long idImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGES.DESCRIPTION
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGES.ID_ELEMENT
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    private Integer idElement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGES.ELEMENT_TYPE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    private Integer elementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.IMAGES.IMAGE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    private byte[] image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGES.ID_IMAGE
     *
     * @return the value of PUBLIC.IMAGES.ID_IMAGE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public Long getIdImage() {
        return idImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGES.ID_IMAGE
     *
     * @param idImage the value for PUBLIC.IMAGES.ID_IMAGE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public void setIdImage(Long idImage) {
        this.idImage = idImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGES.DESCRIPTION
     *
     * @return the value of PUBLIC.IMAGES.DESCRIPTION
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGES.DESCRIPTION
     *
     * @param description the value for PUBLIC.IMAGES.DESCRIPTION
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGES.ID_ELEMENT
     *
     * @return the value of PUBLIC.IMAGES.ID_ELEMENT
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public Integer getIdElement() {
        return idElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGES.ID_ELEMENT
     *
     * @param idElement the value for PUBLIC.IMAGES.ID_ELEMENT
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public void setIdElement(Integer idElement) {
        this.idElement = idElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGES.ELEMENT_TYPE
     *
     * @return the value of PUBLIC.IMAGES.ELEMENT_TYPE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public Integer getElementType() {
        return elementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGES.ELEMENT_TYPE
     *
     * @param elementType the value for PUBLIC.IMAGES.ELEMENT_TYPE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public void setElementType(Integer elementType) {
        this.elementType = elementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.IMAGES.IMAGE
     *
     * @return the value of PUBLIC.IMAGES.IMAGE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.IMAGES.IMAGE
     *
     * @param image the value for PUBLIC.IMAGES.IMAGE
     *
     * @mbggenerated Wed Jul 10 08:08:05 CEST 2013
     */
    public void setImage(byte[] image) {
        this.image = image;
    }
}