package com.bibisco.dao.model;

public class SceneRevisionCharacters {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SCENE_REVISION_CHARACTERS.ID_CHARACTER
     *
     * @mbggenerated Wed Jul 24 20:46:53 CEST 2013
     */
    private Integer idCharacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SCENE_REVISION_CHARACTERS.ID_SCENE_REVISION
     *
     * @mbggenerated Wed Jul 24 20:46:53 CEST 2013
     */
    private Integer idSceneRevision;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SCENE_REVISION_CHARACTERS.ID_CHARACTER
     *
     * @return the value of PUBLIC.SCENE_REVISION_CHARACTERS.ID_CHARACTER
     *
     * @mbggenerated Wed Jul 24 20:46:53 CEST 2013
     */
    public Integer getIdCharacter() {
        return idCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SCENE_REVISION_CHARACTERS.ID_CHARACTER
     *
     * @param idCharacter the value for PUBLIC.SCENE_REVISION_CHARACTERS.ID_CHARACTER
     *
     * @mbggenerated Wed Jul 24 20:46:53 CEST 2013
     */
    public void setIdCharacter(Integer idCharacter) {
        this.idCharacter = idCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SCENE_REVISION_CHARACTERS.ID_SCENE_REVISION
     *
     * @return the value of PUBLIC.SCENE_REVISION_CHARACTERS.ID_SCENE_REVISION
     *
     * @mbggenerated Wed Jul 24 20:46:53 CEST 2013
     */
    public Integer getIdSceneRevision() {
        return idSceneRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SCENE_REVISION_CHARACTERS.ID_SCENE_REVISION
     *
     * @param idSceneRevision the value for PUBLIC.SCENE_REVISION_CHARACTERS.ID_SCENE_REVISION
     *
     * @mbggenerated Wed Jul 24 20:46:53 CEST 2013
     */
    public void setIdSceneRevision(Integer idSceneRevision) {
        this.idSceneRevision = idSceneRevision;
    }
}