package com.bibisco.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SceneRevisionsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public SceneRevisionsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdSceneRevisionIsNull() {
			addCriterion("ID_SCENE_REVISION is null");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionIsNotNull() {
			addCriterion("ID_SCENE_REVISION is not null");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION =", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionNotEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION <>", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionGreaterThan(Long value) {
			addCriterion("ID_SCENE_REVISION >", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION >=", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionLessThan(Long value) {
			addCriterion("ID_SCENE_REVISION <", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionLessThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION <=", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionIn(List<Long> values) {
			addCriterion("ID_SCENE_REVISION in", values, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionNotIn(List<Long> values) {
			addCriterion("ID_SCENE_REVISION not in", values, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE_REVISION between", value1, value2, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionNotBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE_REVISION not between", value1, value2, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdLocationIsNull() {
			addCriterion("ID_LOCATION is null");
			return (Criteria) this;
		}

		public Criteria andIdLocationIsNotNull() {
			addCriterion("ID_LOCATION is not null");
			return (Criteria) this;
		}

		public Criteria andIdLocationEqualTo(Integer value) {
			addCriterion("ID_LOCATION =", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationNotEqualTo(Integer value) {
			addCriterion("ID_LOCATION <>", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationGreaterThan(Integer value) {
			addCriterion("ID_LOCATION >", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_LOCATION >=", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationLessThan(Integer value) {
			addCriterion("ID_LOCATION <", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationLessThanOrEqualTo(Integer value) {
			addCriterion("ID_LOCATION <=", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationIn(List<Integer> values) {
			addCriterion("ID_LOCATION in", values, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationNotIn(List<Integer> values) {
			addCriterion("ID_LOCATION not in", values, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationBetween(Integer value1, Integer value2) {
			addCriterion("ID_LOCATION between", value1, value2, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_LOCATION not between", value1, value2, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdSceneIsNull() {
			addCriterion("ID_SCENE is null");
			return (Criteria) this;
		}

		public Criteria andIdSceneIsNotNull() {
			addCriterion("ID_SCENE is not null");
			return (Criteria) this;
		}

		public Criteria andIdSceneEqualTo(Integer value) {
			addCriterion("ID_SCENE =", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotEqualTo(Integer value) {
			addCriterion("ID_SCENE <>", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneGreaterThan(Integer value) {
			addCriterion("ID_SCENE >", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_SCENE >=", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneLessThan(Integer value) {
			addCriterion("ID_SCENE <", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneLessThanOrEqualTo(Integer value) {
			addCriterion("ID_SCENE <=", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneIn(List<Integer> values) {
			addCriterion("ID_SCENE in", values, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotIn(List<Integer> values) {
			addCriterion("ID_SCENE not in", values, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneBetween(Integer value1, Integer value2) {
			addCriterion("ID_SCENE between", value1, value2, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_SCENE not between", value1, value2, "idScene");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterIsNull() {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER is null");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterIsNotNull() {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER is not null");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER =", value, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterNotEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER <>", value, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterGreaterThan(Integer value) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER >", value, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterGreaterThanOrEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER >=", value, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterLessThan(Integer value) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER <", value, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterLessThanOrEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER <=", value, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterIn(List<Integer> values) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER in", values, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterNotIn(List<Integer> values) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER not in", values, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterBetween(Integer value1, Integer value2) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER between", value1, value2, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIdCharacterNotBetween(Integer value1, Integer value2) {
			addCriterion("POINT_OF_VIEW_ID_CHARACTER not between", value1, value2, "pointOfViewIdCharacter");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberIsNull() {
			addCriterion("REVISION_NUMBER is null");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberIsNotNull() {
			addCriterion("REVISION_NUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberEqualTo(Integer value) {
			addCriterion("REVISION_NUMBER =", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberNotEqualTo(Integer value) {
			addCriterion("REVISION_NUMBER <>", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberGreaterThan(Integer value) {
			addCriterion("REVISION_NUMBER >", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("REVISION_NUMBER >=", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberLessThan(Integer value) {
			addCriterion("REVISION_NUMBER <", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberLessThanOrEqualTo(Integer value) {
			addCriterion("REVISION_NUMBER <=", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberIn(List<Integer> values) {
			addCriterion("REVISION_NUMBER in", values, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberNotIn(List<Integer> values) {
			addCriterion("REVISION_NUMBER not in", values, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberBetween(Integer value1, Integer value2) {
			addCriterion("REVISION_NUMBER between", value1, value2, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("REVISION_NUMBER not between", value1, value2, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andSceneDateIsNull() {
			addCriterion("SCENE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSceneDateIsNotNull() {
			addCriterion("SCENE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSceneDateEqualTo(Date value) {
			addCriterion("SCENE_DATE =", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateNotEqualTo(Date value) {
			addCriterion("SCENE_DATE <>", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateGreaterThan(Date value) {
			addCriterion("SCENE_DATE >", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateGreaterThanOrEqualTo(Date value) {
			addCriterion("SCENE_DATE >=", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateLessThan(Date value) {
			addCriterion("SCENE_DATE <", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateLessThanOrEqualTo(Date value) {
			addCriterion("SCENE_DATE <=", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateIn(List<Date> values) {
			addCriterion("SCENE_DATE in", values, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateNotIn(List<Date> values) {
			addCriterion("SCENE_DATE not in", values, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateBetween(Date value1, Date value2) {
			addCriterion("SCENE_DATE between", value1, value2, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateNotBetween(Date value1, Date value2) {
			addCriterion("SCENE_DATE not between", value1, value2, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSelectedIsNull() {
			addCriterion("SELECTED is null");
			return (Criteria) this;
		}

		public Criteria andSelectedIsNotNull() {
			addCriterion("SELECTED is not null");
			return (Criteria) this;
		}

		public Criteria andSelectedEqualTo(String value) {
			addCriterion("SELECTED =", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotEqualTo(String value) {
			addCriterion("SELECTED <>", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedGreaterThan(String value) {
			addCriterion("SELECTED >", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedGreaterThanOrEqualTo(String value) {
			addCriterion("SELECTED >=", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedLessThan(String value) {
			addCriterion("SELECTED <", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedLessThanOrEqualTo(String value) {
			addCriterion("SELECTED <=", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedLike(String value) {
			addCriterion("SELECTED like", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotLike(String value) {
			addCriterion("SELECTED not like", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedIn(List<String> values) {
			addCriterion("SELECTED in", values, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotIn(List<String> values) {
			addCriterion("SELECTED not in", values, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedBetween(String value1, String value2) {
			addCriterion("SELECTED between", value1, value2, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotBetween(String value1, String value2) {
			addCriterion("SELECTED not between", value1, value2, "selected");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIsNull() {
			addCriterion("POINT_OF_VIEW is null");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIsNotNull() {
			addCriterion("POINT_OF_VIEW is not null");
			return (Criteria) this;
		}

		public Criteria andPointOfViewEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW =", value, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewNotEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW <>", value, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewGreaterThan(Integer value) {
			addCriterion("POINT_OF_VIEW >", value, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewGreaterThanOrEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW >=", value, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewLessThan(Integer value) {
			addCriterion("POINT_OF_VIEW <", value, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewLessThanOrEqualTo(Integer value) {
			addCriterion("POINT_OF_VIEW <=", value, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewIn(List<Integer> values) {
			addCriterion("POINT_OF_VIEW in", values, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewNotIn(List<Integer> values) {
			addCriterion("POINT_OF_VIEW not in", values, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewBetween(Integer value1, Integer value2) {
			addCriterion("POINT_OF_VIEW between", value1, value2, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andPointOfViewNotBetween(Integer value1, Integer value2) {
			addCriterion("POINT_OF_VIEW not between", value1, value2, "pointOfView");
			return (Criteria) this;
		}

		public Criteria andTenseIsNull() {
			addCriterion("TENSE is null");
			return (Criteria) this;
		}

		public Criteria andTenseIsNotNull() {
			addCriterion("TENSE is not null");
			return (Criteria) this;
		}

		public Criteria andTenseEqualTo(String value) {
			addCriterion("TENSE =", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseNotEqualTo(String value) {
			addCriterion("TENSE <>", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseGreaterThan(String value) {
			addCriterion("TENSE >", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseGreaterThanOrEqualTo(String value) {
			addCriterion("TENSE >=", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseLessThan(String value) {
			addCriterion("TENSE <", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseLessThanOrEqualTo(String value) {
			addCriterion("TENSE <=", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseLike(String value) {
			addCriterion("TENSE like", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseNotLike(String value) {
			addCriterion("TENSE not like", value, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseIn(List<String> values) {
			addCriterion("TENSE in", values, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseNotIn(List<String> values) {
			addCriterion("TENSE not in", values, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseBetween(String value1, String value2) {
			addCriterion("TENSE between", value1, value2, "tense");
			return (Criteria) this;
		}

		public Criteria andTenseNotBetween(String value1, String value2) {
			addCriterion("TENSE not between", value1, value2, "tense");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.SCENE_REVISIONS
	 * @mbggenerated  Thu Jul 25 22:54:27 CEST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.SCENE_REVISIONS
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 23:27:08 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}