package com.bibisco.dao.model;


public class VChapters {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.ID_CHAPTER
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private Long idChapter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.TITLE
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.POSITION
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private Integer position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.REASON_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private Integer reasonTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.MIN_SCENES_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private Integer minScenesTaskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.MAX_SCENES_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private Integer maxScenesTaskStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.ID_CHAPTER
	 * @return  the value of PUBLIC.V_CHAPTERS.ID_CHAPTER
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public Long getIdChapter() {
		return idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.ID_CHAPTER
	 * @param idChapter  the value for PUBLIC.V_CHAPTERS.ID_CHAPTER
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setIdChapter(Long idChapter) {
		this.idChapter = idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.TITLE
	 * @return  the value of PUBLIC.V_CHAPTERS.TITLE
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.TITLE
	 * @param title  the value for PUBLIC.V_CHAPTERS.TITLE
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.POSITION
	 * @return  the value of PUBLIC.V_CHAPTERS.POSITION
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.POSITION
	 * @param position  the value for PUBLIC.V_CHAPTERS.POSITION
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.REASON_TASK_STATUS
	 * @return  the value of PUBLIC.V_CHAPTERS.REASON_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public Integer getReasonTaskStatus() {
		return reasonTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.REASON_TASK_STATUS
	 * @param reasonTaskStatus  the value for PUBLIC.V_CHAPTERS.REASON_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setReasonTaskStatus(Integer reasonTaskStatus) {
		this.reasonTaskStatus = reasonTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.MIN_SCENES_TASK_STATUS
	 * @return  the value of PUBLIC.V_CHAPTERS.MIN_SCENES_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public Integer getMinScenesTaskStatus() {
		return minScenesTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.MIN_SCENES_TASK_STATUS
	 * @param minScenesTaskStatus  the value for PUBLIC.V_CHAPTERS.MIN_SCENES_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setMinScenesTaskStatus(Integer minScenesTaskStatus) {
		this.minScenesTaskStatus = minScenesTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.MAX_SCENES_TASK_STATUS
	 * @return  the value of PUBLIC.V_CHAPTERS.MAX_SCENES_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public Integer getMaxScenesTaskStatus() {
		return maxScenesTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.MAX_SCENES_TASK_STATUS
	 * @param maxScenesTaskStatus  the value for PUBLIC.V_CHAPTERS.MAX_SCENES_TASK_STATUS
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setMaxScenesTaskStatus(Integer maxScenesTaskStatus) {
		this.maxScenesTaskStatus = maxScenesTaskStatus;
	}
}