package com.bibisco.dao.model;

public class VChaptersWithBLOBs extends VChapters {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.REASON
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHAPTERS.NOTE
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.REASON
	 * @return  the value of PUBLIC.V_CHAPTERS.REASON
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.REASON
	 * @param reason  the value for PUBLIC.V_CHAPTERS.REASON
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHAPTERS.NOTE
	 * @return  the value of PUBLIC.V_CHAPTERS.NOTE
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHAPTERS.NOTE
	 * @param note  the value for PUBLIC.V_CHAPTERS.NOTE
	 * @mbggenerated  Sat Jun 22 10:00:35 CEST 2013
	 */
	public void setNote(String note) {
		this.note = note;
	}
}