package com.bibisco.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VCharacterSceneExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public VCharacterSceneExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdChapterIsNull() {
			addCriterion("ID_CHAPTER is null");
			return (Criteria) this;
		}

		public Criteria andIdChapterIsNotNull() {
			addCriterion("ID_CHAPTER is not null");
			return (Criteria) this;
		}

		public Criteria andIdChapterEqualTo(Long value) {
			addCriterion("ID_CHAPTER =", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterNotEqualTo(Long value) {
			addCriterion("ID_CHAPTER <>", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterGreaterThan(Long value) {
			addCriterion("ID_CHAPTER >", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_CHAPTER >=", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterLessThan(Long value) {
			addCriterion("ID_CHAPTER <", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterLessThanOrEqualTo(Long value) {
			addCriterion("ID_CHAPTER <=", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterIn(List<Long> values) {
			addCriterion("ID_CHAPTER in", values, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterNotIn(List<Long> values) {
			addCriterion("ID_CHAPTER not in", values, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterBetween(Long value1, Long value2) {
			addCriterion("ID_CHAPTER between", value1, value2, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterNotBetween(Long value1, Long value2) {
			addCriterion("ID_CHAPTER not between", value1, value2, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdSceneIsNull() {
			addCriterion("ID_SCENE is null");
			return (Criteria) this;
		}

		public Criteria andIdSceneIsNotNull() {
			addCriterion("ID_SCENE is not null");
			return (Criteria) this;
		}

		public Criteria andIdSceneEqualTo(Long value) {
			addCriterion("ID_SCENE =", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotEqualTo(Long value) {
			addCriterion("ID_SCENE <>", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneGreaterThan(Long value) {
			addCriterion("ID_SCENE >", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE >=", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneLessThan(Long value) {
			addCriterion("ID_SCENE <", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneLessThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE <=", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneIn(List<Long> values) {
			addCriterion("ID_SCENE in", values, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotIn(List<Long> values) {
			addCriterion("ID_SCENE not in", values, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE between", value1, value2, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE not between", value1, value2, "idScene");
			return (Criteria) this;
		}

		public Criteria andScenePositionIsNull() {
			addCriterion("SCENE_POSITION is null");
			return (Criteria) this;
		}

		public Criteria andScenePositionIsNotNull() {
			addCriterion("SCENE_POSITION is not null");
			return (Criteria) this;
		}

		public Criteria andScenePositionEqualTo(Integer value) {
			addCriterion("SCENE_POSITION =", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionNotEqualTo(Integer value) {
			addCriterion("SCENE_POSITION <>", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionGreaterThan(Integer value) {
			addCriterion("SCENE_POSITION >", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("SCENE_POSITION >=", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionLessThan(Integer value) {
			addCriterion("SCENE_POSITION <", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionLessThanOrEqualTo(Integer value) {
			addCriterion("SCENE_POSITION <=", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionIn(List<Integer> values) {
			addCriterion("SCENE_POSITION in", values, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionNotIn(List<Integer> values) {
			addCriterion("SCENE_POSITION not in", values, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionBetween(Integer value1, Integer value2) {
			addCriterion("SCENE_POSITION between", value1, value2, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionNotBetween(Integer value1, Integer value2) {
			addCriterion("SCENE_POSITION not between", value1, value2, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionIsNull() {
			addCriterion("CHAPTER_POSITION is null");
			return (Criteria) this;
		}

		public Criteria andChapterPositionIsNotNull() {
			addCriterion("CHAPTER_POSITION is not null");
			return (Criteria) this;
		}

		public Criteria andChapterPositionEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION =", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionNotEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION <>", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionGreaterThan(Integer value) {
			addCriterion("CHAPTER_POSITION >", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION >=", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionLessThan(Integer value) {
			addCriterion("CHAPTER_POSITION <", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionLessThanOrEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION <=", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionIn(List<Integer> values) {
			addCriterion("CHAPTER_POSITION in", values, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionNotIn(List<Integer> values) {
			addCriterion("CHAPTER_POSITION not in", values, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionBetween(Integer value1, Integer value2) {
			addCriterion("CHAPTER_POSITION between", value1, value2, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionNotBetween(Integer value1, Integer value2) {
			addCriterion("CHAPTER_POSITION not between", value1, value2, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterTitleIsNull() {
			addCriterion("CHAPTER_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andChapterTitleIsNotNull() {
			addCriterion("CHAPTER_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andChapterTitleEqualTo(String value) {
			addCriterion("CHAPTER_TITLE =", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotEqualTo(String value) {
			addCriterion("CHAPTER_TITLE <>", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleGreaterThan(String value) {
			addCriterion("CHAPTER_TITLE >", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleGreaterThanOrEqualTo(String value) {
			addCriterion("CHAPTER_TITLE >=", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleLessThan(String value) {
			addCriterion("CHAPTER_TITLE <", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleLessThanOrEqualTo(String value) {
			addCriterion("CHAPTER_TITLE <=", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleLike(String value) {
			addCriterion("CHAPTER_TITLE like", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotLike(String value) {
			addCriterion("CHAPTER_TITLE not like", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleIn(List<String> values) {
			addCriterion("CHAPTER_TITLE in", values, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotIn(List<String> values) {
			addCriterion("CHAPTER_TITLE not in", values, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleBetween(String value1, String value2) {
			addCriterion("CHAPTER_TITLE between", value1, value2, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotBetween(String value1, String value2) {
			addCriterion("CHAPTER_TITLE not between", value1, value2, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionIsNull() {
			addCriterion("SCENE_DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionIsNotNull() {
			addCriterion("SCENE_DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION =", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION <>", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionGreaterThan(String value) {
			addCriterion("SCENE_DESCRIPTION >", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION >=", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionLessThan(String value) {
			addCriterion("SCENE_DESCRIPTION <", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionLessThanOrEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION <=", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionLike(String value) {
			addCriterion("SCENE_DESCRIPTION like", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotLike(String value) {
			addCriterion("SCENE_DESCRIPTION not like", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionIn(List<String> values) {
			addCriterion("SCENE_DESCRIPTION in", values, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotIn(List<String> values) {
			addCriterion("SCENE_DESCRIPTION not in", values, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionBetween(String value1, String value2) {
			addCriterion("SCENE_DESCRIPTION between", value1, value2, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotBetween(String value1, String value2) {
			addCriterion("SCENE_DESCRIPTION not between", value1, value2, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andCharacterNameIsNull() {
			addCriterion("CHARACTER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andCharacterNameIsNotNull() {
			addCriterion("CHARACTER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andCharacterNameEqualTo(String value) {
			addCriterion("CHARACTER_NAME =", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameNotEqualTo(String value) {
			addCriterion("CHARACTER_NAME <>", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameGreaterThan(String value) {
			addCriterion("CHARACTER_NAME >", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHARACTER_NAME >=", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameLessThan(String value) {
			addCriterion("CHARACTER_NAME <", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameLessThanOrEqualTo(String value) {
			addCriterion("CHARACTER_NAME <=", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameLike(String value) {
			addCriterion("CHARACTER_NAME like", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameNotLike(String value) {
			addCriterion("CHARACTER_NAME not like", value, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameIn(List<String> values) {
			addCriterion("CHARACTER_NAME in", values, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameNotIn(List<String> values) {
			addCriterion("CHARACTER_NAME not in", values, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameBetween(String value1, String value2) {
			addCriterion("CHARACTER_NAME between", value1, value2, "characterName");
			return (Criteria) this;
		}

		public Criteria andCharacterNameNotBetween(String value1, String value2) {
			addCriterion("CHARACTER_NAME not between", value1, value2, "characterName");
			return (Criteria) this;
		}

		public Criteria andIdCharacterIsNull() {
			addCriterion("ID_CHARACTER is null");
			return (Criteria) this;
		}

		public Criteria andIdCharacterIsNotNull() {
			addCriterion("ID_CHARACTER is not null");
			return (Criteria) this;
		}

		public Criteria andIdCharacterEqualTo(Long value) {
			addCriterion("ID_CHARACTER =", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterNotEqualTo(Long value) {
			addCriterion("ID_CHARACTER <>", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterGreaterThan(Long value) {
			addCriterion("ID_CHARACTER >", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_CHARACTER >=", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterLessThan(Long value) {
			addCriterion("ID_CHARACTER <", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterLessThanOrEqualTo(Long value) {
			addCriterion("ID_CHARACTER <=", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterIn(List<Long> values) {
			addCriterion("ID_CHARACTER in", values, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterNotIn(List<Long> values) {
			addCriterion("ID_CHARACTER not in", values, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterBetween(Long value1, Long value2) {
			addCriterion("ID_CHARACTER between", value1, value2, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterNotBetween(Long value1, Long value2) {
			addCriterion("ID_CHARACTER not between", value1, value2, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterIsNull() {
			addCriterion("MAIN_CHARACTER is null");
			return (Criteria) this;
		}

		public Criteria andMainCharacterIsNotNull() {
			addCriterion("MAIN_CHARACTER is not null");
			return (Criteria) this;
		}

		public Criteria andMainCharacterEqualTo(String value) {
			addCriterion("MAIN_CHARACTER =", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotEqualTo(String value) {
			addCriterion("MAIN_CHARACTER <>", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterGreaterThan(String value) {
			addCriterion("MAIN_CHARACTER >", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterGreaterThanOrEqualTo(String value) {
			addCriterion("MAIN_CHARACTER >=", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterLessThan(String value) {
			addCriterion("MAIN_CHARACTER <", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterLessThanOrEqualTo(String value) {
			addCriterion("MAIN_CHARACTER <=", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterLike(String value) {
			addCriterion("MAIN_CHARACTER like", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotLike(String value) {
			addCriterion("MAIN_CHARACTER not like", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterIn(List<String> values) {
			addCriterion("MAIN_CHARACTER in", values, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotIn(List<String> values) {
			addCriterion("MAIN_CHARACTER not in", values, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterBetween(String value1, String value2) {
			addCriterion("MAIN_CHARACTER between", value1, value2, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotBetween(String value1, String value2) {
			addCriterion("MAIN_CHARACTER not between", value1, value2, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionIsNull() {
			addCriterion("CHARACTER_POSITION is null");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionIsNotNull() {
			addCriterion("CHARACTER_POSITION is not null");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionEqualTo(Integer value) {
			addCriterion("CHARACTER_POSITION =", value, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionNotEqualTo(Integer value) {
			addCriterion("CHARACTER_POSITION <>", value, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionGreaterThan(Integer value) {
			addCriterion("CHARACTER_POSITION >", value, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHARACTER_POSITION >=", value, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionLessThan(Integer value) {
			addCriterion("CHARACTER_POSITION <", value, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionLessThanOrEqualTo(Integer value) {
			addCriterion("CHARACTER_POSITION <=", value, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionIn(List<Integer> values) {
			addCriterion("CHARACTER_POSITION in", values, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionNotIn(List<Integer> values) {
			addCriterion("CHARACTER_POSITION not in", values, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionBetween(Integer value1, Integer value2) {
			addCriterion("CHARACTER_POSITION between", value1, value2, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andCharacterPositionNotBetween(Integer value1, Integer value2) {
			addCriterion("CHARACTER_POSITION not between", value1, value2, "characterPosition");
			return (Criteria) this;
		}

		public Criteria andIdLocationIsNull() {
			addCriterion("ID_LOCATION is null");
			return (Criteria) this;
		}

		public Criteria andIdLocationIsNotNull() {
			addCriterion("ID_LOCATION is not null");
			return (Criteria) this;
		}

		public Criteria andIdLocationEqualTo(Long value) {
			addCriterion("ID_LOCATION =", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationNotEqualTo(Long value) {
			addCriterion("ID_LOCATION <>", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationGreaterThan(Long value) {
			addCriterion("ID_LOCATION >", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_LOCATION >=", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationLessThan(Long value) {
			addCriterion("ID_LOCATION <", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationLessThanOrEqualTo(Long value) {
			addCriterion("ID_LOCATION <=", value, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationIn(List<Long> values) {
			addCriterion("ID_LOCATION in", values, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationNotIn(List<Long> values) {
			addCriterion("ID_LOCATION not in", values, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationBetween(Long value1, Long value2) {
			addCriterion("ID_LOCATION between", value1, value2, "idLocation");
			return (Criteria) this;
		}

		public Criteria andIdLocationNotBetween(Long value1, Long value2) {
			addCriterion("ID_LOCATION not between", value1, value2, "idLocation");
			return (Criteria) this;
		}

		public Criteria andLocationNameIsNull() {
			addCriterion("LOCATION_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLocationNameIsNotNull() {
			addCriterion("LOCATION_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLocationNameEqualTo(String value) {
			addCriterion("LOCATION_NAME =", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameNotEqualTo(String value) {
			addCriterion("LOCATION_NAME <>", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameGreaterThan(String value) {
			addCriterion("LOCATION_NAME >", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameGreaterThanOrEqualTo(String value) {
			addCriterion("LOCATION_NAME >=", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameLessThan(String value) {
			addCriterion("LOCATION_NAME <", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameLessThanOrEqualTo(String value) {
			addCriterion("LOCATION_NAME <=", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameLike(String value) {
			addCriterion("LOCATION_NAME like", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameNotLike(String value) {
			addCriterion("LOCATION_NAME not like", value, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameIn(List<String> values) {
			addCriterion("LOCATION_NAME in", values, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameNotIn(List<String> values) {
			addCriterion("LOCATION_NAME not in", values, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameBetween(String value1, String value2) {
			addCriterion("LOCATION_NAME between", value1, value2, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNameNotBetween(String value1, String value2) {
			addCriterion("LOCATION_NAME not between", value1, value2, "locationName");
			return (Criteria) this;
		}

		public Criteria andLocationNationIsNull() {
			addCriterion("LOCATION_NATION is null");
			return (Criteria) this;
		}

		public Criteria andLocationNationIsNotNull() {
			addCriterion("LOCATION_NATION is not null");
			return (Criteria) this;
		}

		public Criteria andLocationNationEqualTo(String value) {
			addCriterion("LOCATION_NATION =", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationNotEqualTo(String value) {
			addCriterion("LOCATION_NATION <>", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationGreaterThan(String value) {
			addCriterion("LOCATION_NATION >", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationGreaterThanOrEqualTo(String value) {
			addCriterion("LOCATION_NATION >=", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationLessThan(String value) {
			addCriterion("LOCATION_NATION <", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationLessThanOrEqualTo(String value) {
			addCriterion("LOCATION_NATION <=", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationLike(String value) {
			addCriterion("LOCATION_NATION like", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationNotLike(String value) {
			addCriterion("LOCATION_NATION not like", value, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationIn(List<String> values) {
			addCriterion("LOCATION_NATION in", values, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationNotIn(List<String> values) {
			addCriterion("LOCATION_NATION not in", values, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationBetween(String value1, String value2) {
			addCriterion("LOCATION_NATION between", value1, value2, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationNationNotBetween(String value1, String value2) {
			addCriterion("LOCATION_NATION not between", value1, value2, "locationNation");
			return (Criteria) this;
		}

		public Criteria andLocationStateIsNull() {
			addCriterion("LOCATION_STATE is null");
			return (Criteria) this;
		}

		public Criteria andLocationStateIsNotNull() {
			addCriterion("LOCATION_STATE is not null");
			return (Criteria) this;
		}

		public Criteria andLocationStateEqualTo(String value) {
			addCriterion("LOCATION_STATE =", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateNotEqualTo(String value) {
			addCriterion("LOCATION_STATE <>", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateGreaterThan(String value) {
			addCriterion("LOCATION_STATE >", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateGreaterThanOrEqualTo(String value) {
			addCriterion("LOCATION_STATE >=", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateLessThan(String value) {
			addCriterion("LOCATION_STATE <", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateLessThanOrEqualTo(String value) {
			addCriterion("LOCATION_STATE <=", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateLike(String value) {
			addCriterion("LOCATION_STATE like", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateNotLike(String value) {
			addCriterion("LOCATION_STATE not like", value, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateIn(List<String> values) {
			addCriterion("LOCATION_STATE in", values, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateNotIn(List<String> values) {
			addCriterion("LOCATION_STATE not in", values, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateBetween(String value1, String value2) {
			addCriterion("LOCATION_STATE between", value1, value2, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationStateNotBetween(String value1, String value2) {
			addCriterion("LOCATION_STATE not between", value1, value2, "locationState");
			return (Criteria) this;
		}

		public Criteria andLocationCityIsNull() {
			addCriterion("LOCATION_CITY is null");
			return (Criteria) this;
		}

		public Criteria andLocationCityIsNotNull() {
			addCriterion("LOCATION_CITY is not null");
			return (Criteria) this;
		}

		public Criteria andLocationCityEqualTo(String value) {
			addCriterion("LOCATION_CITY =", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityNotEqualTo(String value) {
			addCriterion("LOCATION_CITY <>", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityGreaterThan(String value) {
			addCriterion("LOCATION_CITY >", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityGreaterThanOrEqualTo(String value) {
			addCriterion("LOCATION_CITY >=", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityLessThan(String value) {
			addCriterion("LOCATION_CITY <", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityLessThanOrEqualTo(String value) {
			addCriterion("LOCATION_CITY <=", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityLike(String value) {
			addCriterion("LOCATION_CITY like", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityNotLike(String value) {
			addCriterion("LOCATION_CITY not like", value, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityIn(List<String> values) {
			addCriterion("LOCATION_CITY in", values, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityNotIn(List<String> values) {
			addCriterion("LOCATION_CITY not in", values, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityBetween(String value1, String value2) {
			addCriterion("LOCATION_CITY between", value1, value2, "locationCity");
			return (Criteria) this;
		}

		public Criteria andLocationCityNotBetween(String value1, String value2) {
			addCriterion("LOCATION_CITY not between", value1, value2, "locationCity");
			return (Criteria) this;
		}

		public Criteria andSceneDateIsNull() {
			addCriterion("SCENE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSceneDateIsNotNull() {
			addCriterion("SCENE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSceneDateEqualTo(Date value) {
			addCriterion("SCENE_DATE =", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateNotEqualTo(Date value) {
			addCriterion("SCENE_DATE <>", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateGreaterThan(Date value) {
			addCriterion("SCENE_DATE >", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateGreaterThanOrEqualTo(Date value) {
			addCriterion("SCENE_DATE >=", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateLessThan(Date value) {
			addCriterion("SCENE_DATE <", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateLessThanOrEqualTo(Date value) {
			addCriterion("SCENE_DATE <=", value, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateIn(List<Date> values) {
			addCriterion("SCENE_DATE in", values, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateNotIn(List<Date> values) {
			addCriterion("SCENE_DATE not in", values, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateBetween(Date value1, Date value2) {
			addCriterion("SCENE_DATE between", value1, value2, "sceneDate");
			return (Criteria) this;
		}

		public Criteria andSceneDateNotBetween(Date value1, Date value2) {
			addCriterion("SCENE_DATE not between", value1, value2, "sceneDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.V_CHARACTER_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.V_CHARACTER_SCENE
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 15 00:04:37 CET 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}