package com.bibisco.dao.model;

import java.math.BigDecimal;

public class VCharacterOccurences {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_CHARACTER_OCCURENCES.OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    private BigDecimal occurences;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_CHARACTER_OCCURENCES.ID_CHARACTER
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    private Integer idCharacter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_CHARACTER_OCCURENCES.OCCURENCES
     *
     * @return the value of PUBLIC.V_CHARACTER_OCCURENCES.OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    public BigDecimal getOccurences() {
        return occurences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_CHARACTER_OCCURENCES.OCCURENCES
     *
     * @param occurences the value for PUBLIC.V_CHARACTER_OCCURENCES.OCCURENCES
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    public void setOccurences(BigDecimal occurences) {
        this.occurences = occurences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_CHARACTER_OCCURENCES.ID_CHARACTER
     *
     * @return the value of PUBLIC.V_CHARACTER_OCCURENCES.ID_CHARACTER
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    public Integer getIdCharacter() {
        return idCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_CHARACTER_OCCURENCES.ID_CHARACTER
     *
     * @param idCharacter the value for PUBLIC.V_CHARACTER_OCCURENCES.ID_CHARACTER
     *
     * @mbggenerated Sat Jun 22 17:22:10 CEST 2013
     */
    public void setIdCharacter(Integer idCharacter) {
        this.idCharacter = idCharacter;
    }
}