package com.bibisco.dao.model;

import java.util.Date;

public class VSceneTags {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.ID_CHAPTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Long idChapter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.ID_SCENE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Long idScene;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.SCENE_POSITION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Integer scenePosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.CHAPTER_POSITION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Integer chapterPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.CHAPTER_TITLE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String chapterTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.SCENE_DESCRIPTION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String sceneDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.CHARACTER_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String characterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.ID_CHARACTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Long idCharacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.ID_LOCATION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Long idLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.LOCATION_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String locationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.LOCATION_NATION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String locationNation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.LOCATION_STATE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String locationState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.LOCATION_CITY
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String locationCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.ID_POINT_OF_VIEW_4_ANALYSIS
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String idPointOfView4Analysis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Integer pointOfView;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_ID_CHARACTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Integer pointOfViewIdCharacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_CHARACTER_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String pointOfViewCharacterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.TENSE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String tense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.SCENE_DATE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Date sceneDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.ID_STRAND
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private Long idStrand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_SCENE_TAGS.STRAND_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	private String strandName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.ID_CHAPTER
	 * @return  the value of PUBLIC.V_SCENE_TAGS.ID_CHAPTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Long getIdChapter() {
		return idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.ID_CHAPTER
	 * @param idChapter  the value for PUBLIC.V_SCENE_TAGS.ID_CHAPTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setIdChapter(Long idChapter) {
		this.idChapter = idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.ID_SCENE
	 * @return  the value of PUBLIC.V_SCENE_TAGS.ID_SCENE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Long getIdScene() {
		return idScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.ID_SCENE
	 * @param idScene  the value for PUBLIC.V_SCENE_TAGS.ID_SCENE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setIdScene(Long idScene) {
		this.idScene = idScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.SCENE_POSITION
	 * @return  the value of PUBLIC.V_SCENE_TAGS.SCENE_POSITION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Integer getScenePosition() {
		return scenePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.SCENE_POSITION
	 * @param scenePosition  the value for PUBLIC.V_SCENE_TAGS.SCENE_POSITION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setScenePosition(Integer scenePosition) {
		this.scenePosition = scenePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.CHAPTER_POSITION
	 * @return  the value of PUBLIC.V_SCENE_TAGS.CHAPTER_POSITION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Integer getChapterPosition() {
		return chapterPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.CHAPTER_POSITION
	 * @param chapterPosition  the value for PUBLIC.V_SCENE_TAGS.CHAPTER_POSITION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setChapterPosition(Integer chapterPosition) {
		this.chapterPosition = chapterPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.CHAPTER_TITLE
	 * @return  the value of PUBLIC.V_SCENE_TAGS.CHAPTER_TITLE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getChapterTitle() {
		return chapterTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.CHAPTER_TITLE
	 * @param chapterTitle  the value for PUBLIC.V_SCENE_TAGS.CHAPTER_TITLE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setChapterTitle(String chapterTitle) {
		this.chapterTitle = chapterTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.SCENE_DESCRIPTION
	 * @return  the value of PUBLIC.V_SCENE_TAGS.SCENE_DESCRIPTION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getSceneDescription() {
		return sceneDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.SCENE_DESCRIPTION
	 * @param sceneDescription  the value for PUBLIC.V_SCENE_TAGS.SCENE_DESCRIPTION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setSceneDescription(String sceneDescription) {
		this.sceneDescription = sceneDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.CHARACTER_NAME
	 * @return  the value of PUBLIC.V_SCENE_TAGS.CHARACTER_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getCharacterName() {
		return characterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.CHARACTER_NAME
	 * @param characterName  the value for PUBLIC.V_SCENE_TAGS.CHARACTER_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setCharacterName(String characterName) {
		this.characterName = characterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.ID_CHARACTER
	 * @return  the value of PUBLIC.V_SCENE_TAGS.ID_CHARACTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Long getIdCharacter() {
		return idCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.ID_CHARACTER
	 * @param idCharacter  the value for PUBLIC.V_SCENE_TAGS.ID_CHARACTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setIdCharacter(Long idCharacter) {
		this.idCharacter = idCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.ID_LOCATION
	 * @return  the value of PUBLIC.V_SCENE_TAGS.ID_LOCATION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Long getIdLocation() {
		return idLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.ID_LOCATION
	 * @param idLocation  the value for PUBLIC.V_SCENE_TAGS.ID_LOCATION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setIdLocation(Long idLocation) {
		this.idLocation = idLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_NAME
	 * @return  the value of PUBLIC.V_SCENE_TAGS.LOCATION_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getLocationName() {
		return locationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_NAME
	 * @param locationName  the value for PUBLIC.V_SCENE_TAGS.LOCATION_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_NATION
	 * @return  the value of PUBLIC.V_SCENE_TAGS.LOCATION_NATION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getLocationNation() {
		return locationNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_NATION
	 * @param locationNation  the value for PUBLIC.V_SCENE_TAGS.LOCATION_NATION
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setLocationNation(String locationNation) {
		this.locationNation = locationNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_STATE
	 * @return  the value of PUBLIC.V_SCENE_TAGS.LOCATION_STATE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getLocationState() {
		return locationState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_STATE
	 * @param locationState  the value for PUBLIC.V_SCENE_TAGS.LOCATION_STATE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setLocationState(String locationState) {
		this.locationState = locationState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_CITY
	 * @return  the value of PUBLIC.V_SCENE_TAGS.LOCATION_CITY
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getLocationCity() {
		return locationCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.LOCATION_CITY
	 * @param locationCity  the value for PUBLIC.V_SCENE_TAGS.LOCATION_CITY
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setLocationCity(String locationCity) {
		this.locationCity = locationCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.ID_POINT_OF_VIEW_4_ANALYSIS
	 * @return  the value of PUBLIC.V_SCENE_TAGS.ID_POINT_OF_VIEW_4_ANALYSIS
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getIdPointOfView4Analysis() {
		return idPointOfView4Analysis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.ID_POINT_OF_VIEW_4_ANALYSIS
	 * @param idPointOfView4Analysis  the value for PUBLIC.V_SCENE_TAGS.ID_POINT_OF_VIEW_4_ANALYSIS
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setIdPointOfView4Analysis(String idPointOfView4Analysis) {
		this.idPointOfView4Analysis = idPointOfView4Analysis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW
	 * @return  the value of PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Integer getPointOfView() {
		return pointOfView;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW
	 * @param pointOfView  the value for PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setPointOfView(Integer pointOfView) {
		this.pointOfView = pointOfView;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_ID_CHARACTER
	 * @return  the value of PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_ID_CHARACTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Integer getPointOfViewIdCharacter() {
		return pointOfViewIdCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_ID_CHARACTER
	 * @param pointOfViewIdCharacter  the value for PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_ID_CHARACTER
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setPointOfViewIdCharacter(Integer pointOfViewIdCharacter) {
		this.pointOfViewIdCharacter = pointOfViewIdCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_CHARACTER_NAME
	 * @return  the value of PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_CHARACTER_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getPointOfViewCharacterName() {
		return pointOfViewCharacterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_CHARACTER_NAME
	 * @param pointOfViewCharacterName  the value for PUBLIC.V_SCENE_TAGS.POINT_OF_VIEW_CHARACTER_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setPointOfViewCharacterName(String pointOfViewCharacterName) {
		this.pointOfViewCharacterName = pointOfViewCharacterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.TENSE
	 * @return  the value of PUBLIC.V_SCENE_TAGS.TENSE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getTense() {
		return tense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.TENSE
	 * @param tense  the value for PUBLIC.V_SCENE_TAGS.TENSE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setTense(String tense) {
		this.tense = tense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.SCENE_DATE
	 * @return  the value of PUBLIC.V_SCENE_TAGS.SCENE_DATE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Date getSceneDate() {
		return sceneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.SCENE_DATE
	 * @param sceneDate  the value for PUBLIC.V_SCENE_TAGS.SCENE_DATE
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setSceneDate(Date sceneDate) {
		this.sceneDate = sceneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.ID_STRAND
	 * @return  the value of PUBLIC.V_SCENE_TAGS.ID_STRAND
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public Long getIdStrand() {
		return idStrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.ID_STRAND
	 * @param idStrand  the value for PUBLIC.V_SCENE_TAGS.ID_STRAND
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setIdStrand(Long idStrand) {
		this.idStrand = idStrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_SCENE_TAGS.STRAND_NAME
	 * @return  the value of PUBLIC.V_SCENE_TAGS.STRAND_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public String getStrandName() {
		return strandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_SCENE_TAGS.STRAND_NAME
	 * @param strandName  the value for PUBLIC.V_SCENE_TAGS.STRAND_NAME
	 * @mbggenerated  Thu Nov 14 00:34:03 CET 2013
	 */
	public void setStrandName(String strandName) {
		this.strandName = strandName;
	}
}