package com.bibisco.dao.model;

public class VSelectedSceneRevisions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE_REVISION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    private Long idSceneRevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    private Long idScene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SELECTED
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    private String selected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE_POSITION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    private Integer scenePosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_POSITION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    private Integer chapterPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_TITLE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    private String chapterTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    private String scene;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE_REVISION
     *
     * @return the value of PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE_REVISION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public Long getIdSceneRevision() {
        return idSceneRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE_REVISION
     *
     * @param idSceneRevision the value for PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE_REVISION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public void setIdSceneRevision(Long idSceneRevision) {
        this.idSceneRevision = idSceneRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE
     *
     * @return the value of PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public Long getIdScene() {
        return idScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE
     *
     * @param idScene the value for PUBLIC.V_SELECTED_SCENE_REVISIONS.ID_SCENE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public void setIdScene(Long idScene) {
        this.idScene = idScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SELECTED
     *
     * @return the value of PUBLIC.V_SELECTED_SCENE_REVISIONS.SELECTED
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public String getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SELECTED
     *
     * @param selected the value for PUBLIC.V_SELECTED_SCENE_REVISIONS.SELECTED
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public void setSelected(String selected) {
        this.selected = selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE_POSITION
     *
     * @return the value of PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE_POSITION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public Integer getScenePosition() {
        return scenePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE_POSITION
     *
     * @param scenePosition the value for PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE_POSITION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public void setScenePosition(Integer scenePosition) {
        this.scenePosition = scenePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_POSITION
     *
     * @return the value of PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_POSITION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public Integer getChapterPosition() {
        return chapterPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_POSITION
     *
     * @param chapterPosition the value for PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_POSITION
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public void setChapterPosition(Integer chapterPosition) {
        this.chapterPosition = chapterPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_TITLE
     *
     * @return the value of PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_TITLE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public String getChapterTitle() {
        return chapterTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_TITLE
     *
     * @param chapterTitle the value for PUBLIC.V_SELECTED_SCENE_REVISIONS.CHAPTER_TITLE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public void setChapterTitle(String chapterTitle) {
        this.chapterTitle = chapterTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE
     *
     * @return the value of PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public String getScene() {
        return scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE
     *
     * @param scene the value for PUBLIC.V_SELECTED_SCENE_REVISIONS.SCENE
     *
     * @mbggenerated Fri Aug 23 23:39:01 CEST 2013
     */
    public void setScene(String scene) {
        this.scene = scene;
    }
}