package com.bibisco.dao.model;

public class Chapters {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHAPTERS.ID_CHAPTER
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	private Long idChapter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHAPTERS.TITLE
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHAPTERS.POSITION
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	private Integer position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHAPTERS.REASON_TASK_STATUS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	private Integer reasonTaskStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHAPTERS.ID_CHAPTER
	 * @return  the value of PUBLIC.CHAPTERS.ID_CHAPTER
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public Long getIdChapter() {
		return idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHAPTERS.ID_CHAPTER
	 * @param idChapter  the value for PUBLIC.CHAPTERS.ID_CHAPTER
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public void setIdChapter(Long idChapter) {
		this.idChapter = idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHAPTERS.TITLE
	 * @return  the value of PUBLIC.CHAPTERS.TITLE
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHAPTERS.TITLE
	 * @param title  the value for PUBLIC.CHAPTERS.TITLE
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHAPTERS.POSITION
	 * @return  the value of PUBLIC.CHAPTERS.POSITION
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHAPTERS.POSITION
	 * @param position  the value for PUBLIC.CHAPTERS.POSITION
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHAPTERS.REASON_TASK_STATUS
	 * @return  the value of PUBLIC.CHAPTERS.REASON_TASK_STATUS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public Integer getReasonTaskStatus() {
		return reasonTaskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHAPTERS.REASON_TASK_STATUS
	 * @param reasonTaskStatus  the value for PUBLIC.CHAPTERS.REASON_TASK_STATUS
	 * @mbggenerated  Fri May 31 22:30:33 CEST 2013
	 */
	public void setReasonTaskStatus(Integer reasonTaskStatus) {
		this.reasonTaskStatus = reasonTaskStatus;
	}
}