package com.bibisco.dao.model;

import java.util.ArrayList;
import java.util.List;

public class CharactersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public CharactersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdCharacterIsNull() {
			addCriterion("ID_CHARACTER is null");
			return (Criteria) this;
		}

		public Criteria andIdCharacterIsNotNull() {
			addCriterion("ID_CHARACTER is not null");
			return (Criteria) this;
		}

		public Criteria andIdCharacterEqualTo(Long value) {
			addCriterion("ID_CHARACTER =", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterNotEqualTo(Long value) {
			addCriterion("ID_CHARACTER <>", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterGreaterThan(Long value) {
			addCriterion("ID_CHARACTER >", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_CHARACTER >=", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterLessThan(Long value) {
			addCriterion("ID_CHARACTER <", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterLessThanOrEqualTo(Long value) {
			addCriterion("ID_CHARACTER <=", value, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterIn(List<Long> values) {
			addCriterion("ID_CHARACTER in", values, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterNotIn(List<Long> values) {
			addCriterion("ID_CHARACTER not in", values, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterBetween(Long value1, Long value2) {
			addCriterion("ID_CHARACTER between", value1, value2, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andIdCharacterNotBetween(Long value1, Long value2) {
			addCriterion("ID_CHARACTER not between", value1, value2, "idCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterIsNull() {
			addCriterion("MAIN_CHARACTER is null");
			return (Criteria) this;
		}

		public Criteria andMainCharacterIsNotNull() {
			addCriterion("MAIN_CHARACTER is not null");
			return (Criteria) this;
		}

		public Criteria andMainCharacterEqualTo(String value) {
			addCriterion("MAIN_CHARACTER =", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotEqualTo(String value) {
			addCriterion("MAIN_CHARACTER <>", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterGreaterThan(String value) {
			addCriterion("MAIN_CHARACTER >", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterGreaterThanOrEqualTo(String value) {
			addCriterion("MAIN_CHARACTER >=", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterLessThan(String value) {
			addCriterion("MAIN_CHARACTER <", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterLessThanOrEqualTo(String value) {
			addCriterion("MAIN_CHARACTER <=", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterLike(String value) {
			addCriterion("MAIN_CHARACTER like", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotLike(String value) {
			addCriterion("MAIN_CHARACTER not like", value, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterIn(List<String> values) {
			addCriterion("MAIN_CHARACTER in", values, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotIn(List<String> values) {
			addCriterion("MAIN_CHARACTER not in", values, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterBetween(String value1, String value2) {
			addCriterion("MAIN_CHARACTER between", value1, value2, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andMainCharacterNotBetween(String value1, String value2) {
			addCriterion("MAIN_CHARACTER not between", value1, value2, "mainCharacter");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPositionIsNull() {
			addCriterion("POSITION is null");
			return (Criteria) this;
		}

		public Criteria andPositionIsNotNull() {
			addCriterion("POSITION is not null");
			return (Criteria) this;
		}

		public Criteria andPositionEqualTo(Integer value) {
			addCriterion("POSITION =", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotEqualTo(Integer value) {
			addCriterion("POSITION <>", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThan(Integer value) {
			addCriterion("POSITION >", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("POSITION >=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThan(Integer value) {
			addCriterion("POSITION <", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThanOrEqualTo(Integer value) {
			addCriterion("POSITION <=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionIn(List<Integer> values) {
			addCriterion("POSITION in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotIn(List<Integer> values) {
			addCriterion("POSITION not in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionBetween(Integer value1, Integer value2) {
			addCriterion("POSITION between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotBetween(Integer value1, Integer value2) {
			addCriterion("POSITION not between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusIsNull() {
			addCriterion("PERSONAL_DATA_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusIsNotNull() {
			addCriterion("PERSONAL_DATA_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusEqualTo(Integer value) {
			addCriterion("PERSONAL_DATA_TASK_STATUS =", value, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusNotEqualTo(Integer value) {
			addCriterion("PERSONAL_DATA_TASK_STATUS <>", value, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusGreaterThan(Integer value) {
			addCriterion("PERSONAL_DATA_TASK_STATUS >", value, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PERSONAL_DATA_TASK_STATUS >=", value, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusLessThan(Integer value) {
			addCriterion("PERSONAL_DATA_TASK_STATUS <", value, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PERSONAL_DATA_TASK_STATUS <=", value, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusIn(List<Integer> values) {
			addCriterion("PERSONAL_DATA_TASK_STATUS in", values, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusNotIn(List<Integer> values) {
			addCriterion("PERSONAL_DATA_TASK_STATUS not in", values, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("PERSONAL_DATA_TASK_STATUS between", value1, value2, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PERSONAL_DATA_TASK_STATUS not between", value1, value2, "personalDataTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewIsNull() {
			addCriterion("PERSONAL_DATA_INTERVIEW is null");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewIsNotNull() {
			addCriterion("PERSONAL_DATA_INTERVIEW is not null");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewEqualTo(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW =", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewNotEqualTo(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW <>", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewGreaterThan(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW >", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewGreaterThanOrEqualTo(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW >=", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewLessThan(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW <", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewLessThanOrEqualTo(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW <=", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewLike(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW like", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewNotLike(String value) {
			addCriterion("PERSONAL_DATA_INTERVIEW not like", value, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewIn(List<String> values) {
			addCriterion("PERSONAL_DATA_INTERVIEW in", values, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewNotIn(List<String> values) {
			addCriterion("PERSONAL_DATA_INTERVIEW not in", values, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewBetween(String value1, String value2) {
			addCriterion("PERSONAL_DATA_INTERVIEW between", value1, value2, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPersonalDataInterviewNotBetween(String value1, String value2) {
			addCriterion("PERSONAL_DATA_INTERVIEW not between", value1, value2, "personalDataInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusIsNull() {
			addCriterion("PHYSIONOMY_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusIsNotNull() {
			addCriterion("PHYSIONOMY_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusEqualTo(Integer value) {
			addCriterion("PHYSIONOMY_TASK_STATUS =", value, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusNotEqualTo(Integer value) {
			addCriterion("PHYSIONOMY_TASK_STATUS <>", value, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusGreaterThan(Integer value) {
			addCriterion("PHYSIONOMY_TASK_STATUS >", value, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PHYSIONOMY_TASK_STATUS >=", value, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusLessThan(Integer value) {
			addCriterion("PHYSIONOMY_TASK_STATUS <", value, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PHYSIONOMY_TASK_STATUS <=", value, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusIn(List<Integer> values) {
			addCriterion("PHYSIONOMY_TASK_STATUS in", values, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusNotIn(List<Integer> values) {
			addCriterion("PHYSIONOMY_TASK_STATUS not in", values, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("PHYSIONOMY_TASK_STATUS between", value1, value2, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PHYSIONOMY_TASK_STATUS not between", value1, value2, "physionomyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewIsNull() {
			addCriterion("PHYSIONOMY_INTERVIEW is null");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewIsNotNull() {
			addCriterion("PHYSIONOMY_INTERVIEW is not null");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewEqualTo(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW =", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewNotEqualTo(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW <>", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewGreaterThan(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW >", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewGreaterThanOrEqualTo(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW >=", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewLessThan(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW <", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewLessThanOrEqualTo(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW <=", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewLike(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW like", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewNotLike(String value) {
			addCriterion("PHYSIONOMY_INTERVIEW not like", value, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewIn(List<String> values) {
			addCriterion("PHYSIONOMY_INTERVIEW in", values, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewNotIn(List<String> values) {
			addCriterion("PHYSIONOMY_INTERVIEW not in", values, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewBetween(String value1, String value2) {
			addCriterion("PHYSIONOMY_INTERVIEW between", value1, value2, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPhysionomyInterviewNotBetween(String value1, String value2) {
			addCriterion("PHYSIONOMY_INTERVIEW not between", value1, value2, "physionomyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusIsNull() {
			addCriterion("PSYCHOLOGY_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusIsNotNull() {
			addCriterion("PSYCHOLOGY_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusEqualTo(Integer value) {
			addCriterion("PSYCHOLOGY_TASK_STATUS =", value, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusNotEqualTo(Integer value) {
			addCriterion("PSYCHOLOGY_TASK_STATUS <>", value, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusGreaterThan(Integer value) {
			addCriterion("PSYCHOLOGY_TASK_STATUS >", value, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("PSYCHOLOGY_TASK_STATUS >=", value, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusLessThan(Integer value) {
			addCriterion("PSYCHOLOGY_TASK_STATUS <", value, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("PSYCHOLOGY_TASK_STATUS <=", value, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusIn(List<Integer> values) {
			addCriterion("PSYCHOLOGY_TASK_STATUS in", values, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusNotIn(List<Integer> values) {
			addCriterion("PSYCHOLOGY_TASK_STATUS not in", values, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("PSYCHOLOGY_TASK_STATUS between", value1, value2, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("PSYCHOLOGY_TASK_STATUS not between", value1, value2, "psychologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewIsNull() {
			addCriterion("PSYCHOLOGY_INTERVIEW is null");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewIsNotNull() {
			addCriterion("PSYCHOLOGY_INTERVIEW is not null");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewEqualTo(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW =", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewNotEqualTo(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW <>", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewGreaterThan(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW >", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewGreaterThanOrEqualTo(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW >=", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewLessThan(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW <", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewLessThanOrEqualTo(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW <=", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewLike(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW like", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewNotLike(String value) {
			addCriterion("PSYCHOLOGY_INTERVIEW not like", value, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewIn(List<String> values) {
			addCriterion("PSYCHOLOGY_INTERVIEW in", values, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewNotIn(List<String> values) {
			addCriterion("PSYCHOLOGY_INTERVIEW not in", values, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewBetween(String value1, String value2) {
			addCriterion("PSYCHOLOGY_INTERVIEW between", value1, value2, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andPsychologyInterviewNotBetween(String value1, String value2) {
			addCriterion("PSYCHOLOGY_INTERVIEW not between", value1, value2, "psychologyInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusIsNull() {
			addCriterion("BEHAVIORS_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusIsNotNull() {
			addCriterion("BEHAVIORS_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusEqualTo(Integer value) {
			addCriterion("BEHAVIORS_TASK_STATUS =", value, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusNotEqualTo(Integer value) {
			addCriterion("BEHAVIORS_TASK_STATUS <>", value, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusGreaterThan(Integer value) {
			addCriterion("BEHAVIORS_TASK_STATUS >", value, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("BEHAVIORS_TASK_STATUS >=", value, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusLessThan(Integer value) {
			addCriterion("BEHAVIORS_TASK_STATUS <", value, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("BEHAVIORS_TASK_STATUS <=", value, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusIn(List<Integer> values) {
			addCriterion("BEHAVIORS_TASK_STATUS in", values, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusNotIn(List<Integer> values) {
			addCriterion("BEHAVIORS_TASK_STATUS not in", values, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("BEHAVIORS_TASK_STATUS between", value1, value2, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("BEHAVIORS_TASK_STATUS not between", value1, value2, "behaviorsTaskStatus");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewIsNull() {
			addCriterion("BEHAVIORS_INTERVIEW is null");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewIsNotNull() {
			addCriterion("BEHAVIORS_INTERVIEW is not null");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewEqualTo(String value) {
			addCriterion("BEHAVIORS_INTERVIEW =", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewNotEqualTo(String value) {
			addCriterion("BEHAVIORS_INTERVIEW <>", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewGreaterThan(String value) {
			addCriterion("BEHAVIORS_INTERVIEW >", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewGreaterThanOrEqualTo(String value) {
			addCriterion("BEHAVIORS_INTERVIEW >=", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewLessThan(String value) {
			addCriterion("BEHAVIORS_INTERVIEW <", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewLessThanOrEqualTo(String value) {
			addCriterion("BEHAVIORS_INTERVIEW <=", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewLike(String value) {
			addCriterion("BEHAVIORS_INTERVIEW like", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewNotLike(String value) {
			addCriterion("BEHAVIORS_INTERVIEW not like", value, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewIn(List<String> values) {
			addCriterion("BEHAVIORS_INTERVIEW in", values, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewNotIn(List<String> values) {
			addCriterion("BEHAVIORS_INTERVIEW not in", values, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewBetween(String value1, String value2) {
			addCriterion("BEHAVIORS_INTERVIEW between", value1, value2, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andBehaviorsInterviewNotBetween(String value1, String value2) {
			addCriterion("BEHAVIORS_INTERVIEW not between", value1, value2, "behaviorsInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusIsNull() {
			addCriterion("SOCIOLOGY_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusIsNotNull() {
			addCriterion("SOCIOLOGY_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusEqualTo(Integer value) {
			addCriterion("SOCIOLOGY_TASK_STATUS =", value, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusNotEqualTo(Integer value) {
			addCriterion("SOCIOLOGY_TASK_STATUS <>", value, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusGreaterThan(Integer value) {
			addCriterion("SOCIOLOGY_TASK_STATUS >", value, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("SOCIOLOGY_TASK_STATUS >=", value, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusLessThan(Integer value) {
			addCriterion("SOCIOLOGY_TASK_STATUS <", value, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("SOCIOLOGY_TASK_STATUS <=", value, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusIn(List<Integer> values) {
			addCriterion("SOCIOLOGY_TASK_STATUS in", values, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusNotIn(List<Integer> values) {
			addCriterion("SOCIOLOGY_TASK_STATUS not in", values, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("SOCIOLOGY_TASK_STATUS between", value1, value2, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("SOCIOLOGY_TASK_STATUS not between", value1, value2, "sociologyTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewIsNull() {
			addCriterion("SOCIOLOGY_INTERVIEW is null");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewIsNotNull() {
			addCriterion("SOCIOLOGY_INTERVIEW is not null");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewEqualTo(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW =", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewNotEqualTo(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW <>", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewGreaterThan(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW >", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewGreaterThanOrEqualTo(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW >=", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewLessThan(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW <", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewLessThanOrEqualTo(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW <=", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewLike(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW like", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewNotLike(String value) {
			addCriterion("SOCIOLOGY_INTERVIEW not like", value, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewIn(List<String> values) {
			addCriterion("SOCIOLOGY_INTERVIEW in", values, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewNotIn(List<String> values) {
			addCriterion("SOCIOLOGY_INTERVIEW not in", values, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewBetween(String value1, String value2) {
			addCriterion("SOCIOLOGY_INTERVIEW between", value1, value2, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andSociologyInterviewNotBetween(String value1, String value2) {
			addCriterion("SOCIOLOGY_INTERVIEW not between", value1, value2, "sociologyInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusIsNull() {
			addCriterion("IDEAS_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusIsNotNull() {
			addCriterion("IDEAS_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusEqualTo(Integer value) {
			addCriterion("IDEAS_TASK_STATUS =", value, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusNotEqualTo(Integer value) {
			addCriterion("IDEAS_TASK_STATUS <>", value, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusGreaterThan(Integer value) {
			addCriterion("IDEAS_TASK_STATUS >", value, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("IDEAS_TASK_STATUS >=", value, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusLessThan(Integer value) {
			addCriterion("IDEAS_TASK_STATUS <", value, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("IDEAS_TASK_STATUS <=", value, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusIn(List<Integer> values) {
			addCriterion("IDEAS_TASK_STATUS in", values, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusNotIn(List<Integer> values) {
			addCriterion("IDEAS_TASK_STATUS not in", values, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("IDEAS_TASK_STATUS between", value1, value2, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("IDEAS_TASK_STATUS not between", value1, value2, "ideasTaskStatus");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewIsNull() {
			addCriterion("IDEAS_INTERVIEW is null");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewIsNotNull() {
			addCriterion("IDEAS_INTERVIEW is not null");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewEqualTo(String value) {
			addCriterion("IDEAS_INTERVIEW =", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewNotEqualTo(String value) {
			addCriterion("IDEAS_INTERVIEW <>", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewGreaterThan(String value) {
			addCriterion("IDEAS_INTERVIEW >", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewGreaterThanOrEqualTo(String value) {
			addCriterion("IDEAS_INTERVIEW >=", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewLessThan(String value) {
			addCriterion("IDEAS_INTERVIEW <", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewLessThanOrEqualTo(String value) {
			addCriterion("IDEAS_INTERVIEW <=", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewLike(String value) {
			addCriterion("IDEAS_INTERVIEW like", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewNotLike(String value) {
			addCriterion("IDEAS_INTERVIEW not like", value, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewIn(List<String> values) {
			addCriterion("IDEAS_INTERVIEW in", values, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewNotIn(List<String> values) {
			addCriterion("IDEAS_INTERVIEW not in", values, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewBetween(String value1, String value2) {
			addCriterion("IDEAS_INTERVIEW between", value1, value2, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andIdeasInterviewNotBetween(String value1, String value2) {
			addCriterion("IDEAS_INTERVIEW not between", value1, value2, "ideasInterview");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusIsNull() {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusIsNotNull() {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusEqualTo(Integer value) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS =", value, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusNotEqualTo(Integer value) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS <>", value, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusGreaterThan(Integer value) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS >", value, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS >=", value, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusLessThan(Integer value) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS <", value, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS <=", value, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusIn(List<Integer> values) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS in", values, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusNotIn(List<Integer> values) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS not in", values, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS between", value1, value2, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andLifebeforestorybeginningTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("LIFEBEFORESTORYBEGINNING_TASK_STATUS not between", value1, value2, "lifebeforestorybeginningTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusIsNull() {
			addCriterion("CONFLICT_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusIsNotNull() {
			addCriterion("CONFLICT_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusEqualTo(Integer value) {
			addCriterion("CONFLICT_TASK_STATUS =", value, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusNotEqualTo(Integer value) {
			addCriterion("CONFLICT_TASK_STATUS <>", value, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusGreaterThan(Integer value) {
			addCriterion("CONFLICT_TASK_STATUS >", value, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("CONFLICT_TASK_STATUS >=", value, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusLessThan(Integer value) {
			addCriterion("CONFLICT_TASK_STATUS <", value, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("CONFLICT_TASK_STATUS <=", value, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusIn(List<Integer> values) {
			addCriterion("CONFLICT_TASK_STATUS in", values, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusNotIn(List<Integer> values) {
			addCriterion("CONFLICT_TASK_STATUS not in", values, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("CONFLICT_TASK_STATUS between", value1, value2, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andConflictTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("CONFLICT_TASK_STATUS not between", value1, value2, "conflictTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusIsNull() {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusIsNotNull() {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusEqualTo(Integer value) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS =", value, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusNotEqualTo(Integer value) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS <>", value, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusGreaterThan(Integer value) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS >", value, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS >=", value, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusLessThan(Integer value) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS <", value, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS <=", value, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusIn(List<Integer> values) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS in", values, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusNotIn(List<Integer> values) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS not in", values, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS between", value1, value2, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andEvolutionduringthestoryTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("EVOLUTIONDURINGTHESTORY_TASK_STATUS not between", value1, value2, "evolutionduringthestoryTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusIsNull() {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusIsNotNull() {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusEqualTo(Integer value) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS =", value, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusNotEqualTo(Integer value) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS <>", value, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusGreaterThan(Integer value) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS >", value, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS >=", value, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusLessThan(Integer value) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS <", value, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS <=", value, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusIn(List<Integer> values) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS in", values, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusNotIn(List<Integer> values) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS not in", values, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS between", value1, value2, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSecondaryCharacterDescriptionTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("SECONDARY_CHARACTER_DESCRIPTION_TASK_STATUS not between", value1, value2, "secondaryCharacterDescriptionTaskStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.CHARACTERS
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.CHARACTERS
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 17 21:53:25 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}