package com.bibisco.dao.model;

public class CharacterInfosKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHARACTER_INFOS.CHARACTER_INFO_TYPE
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    private String characterInfoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHARACTER_INFOS.ID_CHARACTER
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    private Integer idCharacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHARACTER_INFOS.QUESTION
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    private Integer question;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHARACTER_INFOS.CHARACTER_INFO_TYPE
     *
     * @return the value of PUBLIC.CHARACTER_INFOS.CHARACTER_INFO_TYPE
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    public String getCharacterInfoType() {
        return characterInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHARACTER_INFOS.CHARACTER_INFO_TYPE
     *
     * @param characterInfoType the value for PUBLIC.CHARACTER_INFOS.CHARACTER_INFO_TYPE
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    public void setCharacterInfoType(String characterInfoType) {
        this.characterInfoType = characterInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHARACTER_INFOS.ID_CHARACTER
     *
     * @return the value of PUBLIC.CHARACTER_INFOS.ID_CHARACTER
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    public Integer getIdCharacter() {
        return idCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHARACTER_INFOS.ID_CHARACTER
     *
     * @param idCharacter the value for PUBLIC.CHARACTER_INFOS.ID_CHARACTER
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    public void setIdCharacter(Integer idCharacter) {
        this.idCharacter = idCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHARACTER_INFOS.QUESTION
     *
     * @return the value of PUBLIC.CHARACTER_INFOS.QUESTION
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    public Integer getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHARACTER_INFOS.QUESTION
     *
     * @param question the value for PUBLIC.CHARACTER_INFOS.QUESTION
     *
     * @mbggenerated Thu Jun 27 00:11:42 CEST 2013
     */
    public void setQuestion(Integer question) {
        this.question = question;
    }
}