package com.bibisco.dao.model;

public class CharactersWithBLOBs extends Characters {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PERSONAL_DATA_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String personalDataFreeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PHYSIONOMY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String physionomyFreeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.PSYCHOLOGY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String psychologyFreeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.BEHAVIORS_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String behaviorsFreeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.SOCIOLOGY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String sociologyFreeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.IDEAS_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String ideasFreeText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String lifebeforestorybeginning;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.CONFLICT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String conflict;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String evolutionduringthestory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	private String secondaryCharacterDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PERSONAL_DATA_FREE_TEXT
	 * @return  the value of PUBLIC.CHARACTERS.PERSONAL_DATA_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getPersonalDataFreeText() {
		return personalDataFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PERSONAL_DATA_FREE_TEXT
	 * @param personalDataFreeText  the value for PUBLIC.CHARACTERS.PERSONAL_DATA_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPersonalDataFreeText(String personalDataFreeText) {
		this.personalDataFreeText = personalDataFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PHYSIONOMY_FREE_TEXT
	 * @return  the value of PUBLIC.CHARACTERS.PHYSIONOMY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getPhysionomyFreeText() {
		return physionomyFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PHYSIONOMY_FREE_TEXT
	 * @param physionomyFreeText  the value for PUBLIC.CHARACTERS.PHYSIONOMY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPhysionomyFreeText(String physionomyFreeText) {
		this.physionomyFreeText = physionomyFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.PSYCHOLOGY_FREE_TEXT
	 * @return  the value of PUBLIC.CHARACTERS.PSYCHOLOGY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getPsychologyFreeText() {
		return psychologyFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.PSYCHOLOGY_FREE_TEXT
	 * @param psychologyFreeText  the value for PUBLIC.CHARACTERS.PSYCHOLOGY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setPsychologyFreeText(String psychologyFreeText) {
		this.psychologyFreeText = psychologyFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.BEHAVIORS_FREE_TEXT
	 * @return  the value of PUBLIC.CHARACTERS.BEHAVIORS_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getBehaviorsFreeText() {
		return behaviorsFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.BEHAVIORS_FREE_TEXT
	 * @param behaviorsFreeText  the value for PUBLIC.CHARACTERS.BEHAVIORS_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setBehaviorsFreeText(String behaviorsFreeText) {
		this.behaviorsFreeText = behaviorsFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.SOCIOLOGY_FREE_TEXT
	 * @return  the value of PUBLIC.CHARACTERS.SOCIOLOGY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getSociologyFreeText() {
		return sociologyFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.SOCIOLOGY_FREE_TEXT
	 * @param sociologyFreeText  the value for PUBLIC.CHARACTERS.SOCIOLOGY_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setSociologyFreeText(String sociologyFreeText) {
		this.sociologyFreeText = sociologyFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.IDEAS_FREE_TEXT
	 * @return  the value of PUBLIC.CHARACTERS.IDEAS_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getIdeasFreeText() {
		return ideasFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.IDEAS_FREE_TEXT
	 * @param ideasFreeText  the value for PUBLIC.CHARACTERS.IDEAS_FREE_TEXT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setIdeasFreeText(String ideasFreeText) {
		this.ideasFreeText = ideasFreeText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING
	 * @return  the value of PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getLifebeforestorybeginning() {
		return lifebeforestorybeginning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING
	 * @param lifebeforestorybeginning  the value for PUBLIC.CHARACTERS.LIFEBEFORESTORYBEGINNING
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setLifebeforestorybeginning(String lifebeforestorybeginning) {
		this.lifebeforestorybeginning = lifebeforestorybeginning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.CONFLICT
	 * @return  the value of PUBLIC.CHARACTERS.CONFLICT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getConflict() {
		return conflict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.CONFLICT
	 * @param conflict  the value for PUBLIC.CHARACTERS.CONFLICT
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setConflict(String conflict) {
		this.conflict = conflict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY
	 * @return  the value of PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getEvolutionduringthestory() {
		return evolutionduringthestory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY
	 * @param evolutionduringthestory  the value for PUBLIC.CHARACTERS.EVOLUTIONDURINGTHESTORY
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setEvolutionduringthestory(String evolutionduringthestory) {
		this.evolutionduringthestory = evolutionduringthestory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION
	 * @return  the value of PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public String getSecondaryCharacterDescription() {
		return secondaryCharacterDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION
	 * @param secondaryCharacterDescription  the value for PUBLIC.CHARACTERS.SECONDARY_CHARACTER_DESCRIPTION
	 * @mbggenerated  Wed Jul 03 07:53:49 CEST 2013
	 */
	public void setSecondaryCharacterDescription(String secondaryCharacterDescription) {
		this.secondaryCharacterDescription = secondaryCharacterDescription;
	}
}