package com.bibisco.dao.model;

public class Locations {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.ID_LOCATION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private Long idLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.NAME
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.POSITION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private Integer position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.NATION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private String nation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.STATE
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.CITY
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.TASK_STATUS
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private Integer taskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.LOCATIONS.DESCRIPTION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.ID_LOCATION
	 * @return  the value of PUBLIC.LOCATIONS.ID_LOCATION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public Long getIdLocation() {
		return idLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.ID_LOCATION
	 * @param idLocation  the value for PUBLIC.LOCATIONS.ID_LOCATION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setIdLocation(Long idLocation) {
		this.idLocation = idLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.NAME
	 * @return  the value of PUBLIC.LOCATIONS.NAME
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.NAME
	 * @param name  the value for PUBLIC.LOCATIONS.NAME
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.POSITION
	 * @return  the value of PUBLIC.LOCATIONS.POSITION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.POSITION
	 * @param position  the value for PUBLIC.LOCATIONS.POSITION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.NATION
	 * @return  the value of PUBLIC.LOCATIONS.NATION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public String getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.NATION
	 * @param nation  the value for PUBLIC.LOCATIONS.NATION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setNation(String nation) {
		this.nation = nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.STATE
	 * @return  the value of PUBLIC.LOCATIONS.STATE
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.STATE
	 * @param state  the value for PUBLIC.LOCATIONS.STATE
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.CITY
	 * @return  the value of PUBLIC.LOCATIONS.CITY
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.CITY
	 * @param city  the value for PUBLIC.LOCATIONS.CITY
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.TASK_STATUS
	 * @return  the value of PUBLIC.LOCATIONS.TASK_STATUS
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public Integer getTaskStatus() {
		return taskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.TASK_STATUS
	 * @param taskStatus  the value for PUBLIC.LOCATIONS.TASK_STATUS
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setTaskStatus(Integer taskStatus) {
		this.taskStatus = taskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.LOCATIONS.DESCRIPTION
	 * @return  the value of PUBLIC.LOCATIONS.DESCRIPTION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.LOCATIONS.DESCRIPTION
	 * @param description  the value for PUBLIC.LOCATIONS.DESCRIPTION
	 * @mbggenerated  Thu Jul 04 20:13:11 CEST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}