package com.bibisco.dao.model;

public class Messages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MESSAGES.ID_MESSAGE
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    private Integer idMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MESSAGES.NUMBER_OF_VIEWS
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    private Integer numberOfViews;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MESSAGES.ID_MESSAGE
     *
     * @return the value of PUBLIC.MESSAGES.ID_MESSAGE
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public Integer getIdMessage() {
        return idMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MESSAGES.ID_MESSAGE
     *
     * @param idMessage the value for PUBLIC.MESSAGES.ID_MESSAGE
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MESSAGES.NUMBER_OF_VIEWS
     *
     * @return the value of PUBLIC.MESSAGES.NUMBER_OF_VIEWS
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public Integer getNumberOfViews() {
        return numberOfViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MESSAGES.NUMBER_OF_VIEWS
     *
     * @param numberOfViews the value for PUBLIC.MESSAGES.NUMBER_OF_VIEWS
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public void setNumberOfViews(Integer numberOfViews) {
        this.numberOfViews = numberOfViews;
    }
}