package com.bibisco.dao.model;

import java.util.ArrayList;
import java.util.List;

public class MessagesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public MessagesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdMessageIsNull() {
            addCriterion("ID_MESSAGE is null");
            return (Criteria) this;
        }

        public Criteria andIdMessageIsNotNull() {
            addCriterion("ID_MESSAGE is not null");
            return (Criteria) this;
        }

        public Criteria andIdMessageEqualTo(Integer value) {
            addCriterion("ID_MESSAGE =", value, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageNotEqualTo(Integer value) {
            addCriterion("ID_MESSAGE <>", value, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageGreaterThan(Integer value) {
            addCriterion("ID_MESSAGE >", value, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_MESSAGE >=", value, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageLessThan(Integer value) {
            addCriterion("ID_MESSAGE <", value, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageLessThanOrEqualTo(Integer value) {
            addCriterion("ID_MESSAGE <=", value, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageIn(List<Integer> values) {
            addCriterion("ID_MESSAGE in", values, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageNotIn(List<Integer> values) {
            addCriterion("ID_MESSAGE not in", values, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageBetween(Integer value1, Integer value2) {
            addCriterion("ID_MESSAGE between", value1, value2, "idMessage");
            return (Criteria) this;
        }

        public Criteria andIdMessageNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_MESSAGE not between", value1, value2, "idMessage");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsIsNull() {
            addCriterion("NUMBER_OF_VIEWS is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsIsNotNull() {
            addCriterion("NUMBER_OF_VIEWS is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsEqualTo(Integer value) {
            addCriterion("NUMBER_OF_VIEWS =", value, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsNotEqualTo(Integer value) {
            addCriterion("NUMBER_OF_VIEWS <>", value, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsGreaterThan(Integer value) {
            addCriterion("NUMBER_OF_VIEWS >", value, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_OF_VIEWS >=", value, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsLessThan(Integer value) {
            addCriterion("NUMBER_OF_VIEWS <", value, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsLessThanOrEqualTo(Integer value) {
            addCriterion("NUMBER_OF_VIEWS <=", value, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsIn(List<Integer> values) {
            addCriterion("NUMBER_OF_VIEWS in", values, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsNotIn(List<Integer> values) {
            addCriterion("NUMBER_OF_VIEWS not in", values, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_OF_VIEWS between", value1, value2, "numberOfViews");
            return (Criteria) this;
        }

        public Criteria andNumberOfViewsNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMBER_OF_VIEWS not between", value1, value2, "numberOfViews");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 28 08:32:55 CET 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.MESSAGES
     *
     * @mbggenerated Thu Nov 28 08:32:55 CET 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}