package com.bibisco.dao.model;

public class Projects {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.PROJECTS.ID_PROJECT
	 * @mbggenerated  Fri Aug 09 07:59:47 CEST 2013
	 */
	private String idProject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.PROJECTS.NAME
	 * @mbggenerated  Fri Aug 09 07:59:47 CEST 2013
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.PROJECTS.ID_PROJECT
	 * @return  the value of PUBLIC.PROJECTS.ID_PROJECT
	 * @mbggenerated  Fri Aug 09 07:59:47 CEST 2013
	 */
	public String getIdProject() {
		return idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.PROJECTS.ID_PROJECT
	 * @param idProject  the value for PUBLIC.PROJECTS.ID_PROJECT
	 * @mbggenerated  Fri Aug 09 07:59:47 CEST 2013
	 */
	public void setIdProject(String idProject) {
		this.idProject = idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.PROJECTS.NAME
	 * @return  the value of PUBLIC.PROJECTS.NAME
	 * @mbggenerated  Fri Aug 09 07:59:47 CEST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.PROJECTS.NAME
	 * @param name  the value for PUBLIC.PROJECTS.NAME
	 * @mbggenerated  Fri Aug 09 07:59:47 CEST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}
}