package com.bibisco.dao.model;

public class Scenes {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.SCENES.ID_SCENE
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	private Long idScene;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.SCENES.ID_CHAPTER
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	private Integer idChapter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.SCENES.DESCRIPTION
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.SCENES.POSITION
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	private Integer position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.SCENES.TASK_STATUS
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	private Integer taskStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.SCENES.ID_SCENE
	 * @return  the value of PUBLIC.SCENES.ID_SCENE
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public Long getIdScene() {
		return idScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.SCENES.ID_SCENE
	 * @param idScene  the value for PUBLIC.SCENES.ID_SCENE
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public void setIdScene(Long idScene) {
		this.idScene = idScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.SCENES.ID_CHAPTER
	 * @return  the value of PUBLIC.SCENES.ID_CHAPTER
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public Integer getIdChapter() {
		return idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.SCENES.ID_CHAPTER
	 * @param idChapter  the value for PUBLIC.SCENES.ID_CHAPTER
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public void setIdChapter(Integer idChapter) {
		this.idChapter = idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.SCENES.DESCRIPTION
	 * @return  the value of PUBLIC.SCENES.DESCRIPTION
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.SCENES.DESCRIPTION
	 * @param description  the value for PUBLIC.SCENES.DESCRIPTION
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.SCENES.POSITION
	 * @return  the value of PUBLIC.SCENES.POSITION
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.SCENES.POSITION
	 * @param position  the value for PUBLIC.SCENES.POSITION
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.SCENES.TASK_STATUS
	 * @return  the value of PUBLIC.SCENES.TASK_STATUS
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public Integer getTaskStatus() {
		return taskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.SCENES.TASK_STATUS
	 * @param taskStatus  the value for PUBLIC.SCENES.TASK_STATUS
	 * @mbggenerated  Wed Jul 24 19:55:25 CEST 2013
	 */
	public void setTaskStatus(Integer taskStatus) {
		this.taskStatus = taskStatus;
	}
}