package com.bibisco.dao.model;

public class SceneRevisionStrandsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SCENE_REVISION_STRANDS.ID_SCENE_REVISION
     *
     * @mbggenerated Wed Jul 24 20:45:12 CEST 2013
     */
    private Integer idSceneRevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SCENE_REVISION_STRANDS.ID_STRAND
     *
     * @mbggenerated Wed Jul 24 20:45:12 CEST 2013
     */
    private Integer idStrand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SCENE_REVISION_STRANDS.ID_SCENE_REVISION
     *
     * @return the value of PUBLIC.SCENE_REVISION_STRANDS.ID_SCENE_REVISION
     *
     * @mbggenerated Wed Jul 24 20:45:12 CEST 2013
     */
    public Integer getIdSceneRevision() {
        return idSceneRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SCENE_REVISION_STRANDS.ID_SCENE_REVISION
     *
     * @param idSceneRevision the value for PUBLIC.SCENE_REVISION_STRANDS.ID_SCENE_REVISION
     *
     * @mbggenerated Wed Jul 24 20:45:12 CEST 2013
     */
    public void setIdSceneRevision(Integer idSceneRevision) {
        this.idSceneRevision = idSceneRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SCENE_REVISION_STRANDS.ID_STRAND
     *
     * @return the value of PUBLIC.SCENE_REVISION_STRANDS.ID_STRAND
     *
     * @mbggenerated Wed Jul 24 20:45:12 CEST 2013
     */
    public Integer getIdStrand() {
        return idStrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SCENE_REVISION_STRANDS.ID_STRAND
     *
     * @param idStrand the value for PUBLIC.SCENE_REVISION_STRANDS.ID_STRAND
     *
     * @mbggenerated Wed Jul 24 20:45:12 CEST 2013
     */
    public void setIdStrand(Integer idStrand) {
        this.idStrand = idStrand;
    }
}