package com.bibisco.dao.model;

public class Strands {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.STRANDS.ID_STRAND
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	private Long idStrand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.STRANDS.NAME
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.STRANDS.POSITION
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	private Integer position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.STRANDS.TASK_STATUS
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	private Integer taskStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.STRANDS.DESCRIPTION
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.STRANDS.ID_STRAND
	 * @return  the value of PUBLIC.STRANDS.ID_STRAND
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public Long getIdStrand() {
		return idStrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.STRANDS.ID_STRAND
	 * @param idStrand  the value for PUBLIC.STRANDS.ID_STRAND
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public void setIdStrand(Long idStrand) {
		this.idStrand = idStrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.STRANDS.NAME
	 * @return  the value of PUBLIC.STRANDS.NAME
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.STRANDS.NAME
	 * @param name  the value for PUBLIC.STRANDS.NAME
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.STRANDS.POSITION
	 * @return  the value of PUBLIC.STRANDS.POSITION
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.STRANDS.POSITION
	 * @param position  the value for PUBLIC.STRANDS.POSITION
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.STRANDS.TASK_STATUS
	 * @return  the value of PUBLIC.STRANDS.TASK_STATUS
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public Integer getTaskStatus() {
		return taskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.STRANDS.TASK_STATUS
	 * @param taskStatus  the value for PUBLIC.STRANDS.TASK_STATUS
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public void setTaskStatus(Integer taskStatus) {
		this.taskStatus = taskStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.STRANDS.DESCRIPTION
	 * @return  the value of PUBLIC.STRANDS.DESCRIPTION
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.STRANDS.DESCRIPTION
	 * @param description  the value for PUBLIC.STRANDS.DESCRIPTION
	 * @mbggenerated  Tue Jul 23 21:29:17 CEST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}