package com.bibisco.dao.model;

import java.util.Date;

public class VCharacterScene {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.ID_CHAPTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Long idChapter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.ID_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Long idScene;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.SCENE_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Integer scenePosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.CHAPTER_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Integer chapterPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.CHAPTER_TITLE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String chapterTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.SCENE_DESCRIPTION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String sceneDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.CHARACTER_NAME
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String characterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.ID_CHARACTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Long idCharacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.MAIN_CHARACTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String mainCharacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.CHARACTER_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Integer characterPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.ID_LOCATION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Long idLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_NAME
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String locationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_NATION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String locationNation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_STATE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String locationState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_CITY
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private String locationCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.V_CHARACTER_SCENE.SCENE_DATE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	private Date sceneDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_CHAPTER
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.ID_CHAPTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Long getIdChapter() {
		return idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_CHAPTER
	 * @param idChapter  the value for PUBLIC.V_CHARACTER_SCENE.ID_CHAPTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setIdChapter(Long idChapter) {
		this.idChapter = idChapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_SCENE
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.ID_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Long getIdScene() {
		return idScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_SCENE
	 * @param idScene  the value for PUBLIC.V_CHARACTER_SCENE.ID_SCENE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setIdScene(Long idScene) {
		this.idScene = idScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.SCENE_POSITION
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.SCENE_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Integer getScenePosition() {
		return scenePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.SCENE_POSITION
	 * @param scenePosition  the value for PUBLIC.V_CHARACTER_SCENE.SCENE_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setScenePosition(Integer scenePosition) {
		this.scenePosition = scenePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.CHAPTER_POSITION
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.CHAPTER_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Integer getChapterPosition() {
		return chapterPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.CHAPTER_POSITION
	 * @param chapterPosition  the value for PUBLIC.V_CHARACTER_SCENE.CHAPTER_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setChapterPosition(Integer chapterPosition) {
		this.chapterPosition = chapterPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.CHAPTER_TITLE
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.CHAPTER_TITLE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getChapterTitle() {
		return chapterTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.CHAPTER_TITLE
	 * @param chapterTitle  the value for PUBLIC.V_CHARACTER_SCENE.CHAPTER_TITLE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setChapterTitle(String chapterTitle) {
		this.chapterTitle = chapterTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.SCENE_DESCRIPTION
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.SCENE_DESCRIPTION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getSceneDescription() {
		return sceneDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.SCENE_DESCRIPTION
	 * @param sceneDescription  the value for PUBLIC.V_CHARACTER_SCENE.SCENE_DESCRIPTION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setSceneDescription(String sceneDescription) {
		this.sceneDescription = sceneDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.CHARACTER_NAME
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.CHARACTER_NAME
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getCharacterName() {
		return characterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.CHARACTER_NAME
	 * @param characterName  the value for PUBLIC.V_CHARACTER_SCENE.CHARACTER_NAME
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setCharacterName(String characterName) {
		this.characterName = characterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_CHARACTER
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.ID_CHARACTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Long getIdCharacter() {
		return idCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_CHARACTER
	 * @param idCharacter  the value for PUBLIC.V_CHARACTER_SCENE.ID_CHARACTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setIdCharacter(Long idCharacter) {
		this.idCharacter = idCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.MAIN_CHARACTER
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.MAIN_CHARACTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getMainCharacter() {
		return mainCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.MAIN_CHARACTER
	 * @param mainCharacter  the value for PUBLIC.V_CHARACTER_SCENE.MAIN_CHARACTER
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setMainCharacter(String mainCharacter) {
		this.mainCharacter = mainCharacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.CHARACTER_POSITION
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.CHARACTER_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Integer getCharacterPosition() {
		return characterPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.CHARACTER_POSITION
	 * @param characterPosition  the value for PUBLIC.V_CHARACTER_SCENE.CHARACTER_POSITION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setCharacterPosition(Integer characterPosition) {
		this.characterPosition = characterPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_LOCATION
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.ID_LOCATION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Long getIdLocation() {
		return idLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.ID_LOCATION
	 * @param idLocation  the value for PUBLIC.V_CHARACTER_SCENE.ID_LOCATION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setIdLocation(Long idLocation) {
		this.idLocation = idLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_NAME
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.LOCATION_NAME
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getLocationName() {
		return locationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_NAME
	 * @param locationName  the value for PUBLIC.V_CHARACTER_SCENE.LOCATION_NAME
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_NATION
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.LOCATION_NATION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getLocationNation() {
		return locationNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_NATION
	 * @param locationNation  the value for PUBLIC.V_CHARACTER_SCENE.LOCATION_NATION
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setLocationNation(String locationNation) {
		this.locationNation = locationNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_STATE
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.LOCATION_STATE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getLocationState() {
		return locationState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_STATE
	 * @param locationState  the value for PUBLIC.V_CHARACTER_SCENE.LOCATION_STATE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setLocationState(String locationState) {
		this.locationState = locationState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_CITY
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.LOCATION_CITY
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public String getLocationCity() {
		return locationCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.LOCATION_CITY
	 * @param locationCity  the value for PUBLIC.V_CHARACTER_SCENE.LOCATION_CITY
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setLocationCity(String locationCity) {
		this.locationCity = locationCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.V_CHARACTER_SCENE.SCENE_DATE
	 * @return  the value of PUBLIC.V_CHARACTER_SCENE.SCENE_DATE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public Date getSceneDate() {
		return sceneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.V_CHARACTER_SCENE.SCENE_DATE
	 * @param sceneDate  the value for PUBLIC.V_CHARACTER_SCENE.SCENE_DATE
	 * @mbggenerated  Fri Nov 15 08:46:22 CET 2013
	 */
	public void setSceneDate(Date sceneDate) {
		this.sceneDate = sceneDate;
	}
}