package com.bibisco.dao.model;

import java.util.ArrayList;
import java.util.List;

public class VSelectedSceneRevisionsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public VSelectedSceneRevisionsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdSceneRevisionIsNull() {
			addCriterion("ID_SCENE_REVISION is null");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionIsNotNull() {
			addCriterion("ID_SCENE_REVISION is not null");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION =", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionNotEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION <>", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionGreaterThan(Long value) {
			addCriterion("ID_SCENE_REVISION >", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION >=", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionLessThan(Long value) {
			addCriterion("ID_SCENE_REVISION <", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionLessThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE_REVISION <=", value, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionIn(List<Long> values) {
			addCriterion("ID_SCENE_REVISION in", values, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionNotIn(List<Long> values) {
			addCriterion("ID_SCENE_REVISION not in", values, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE_REVISION between", value1, value2, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneRevisionNotBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE_REVISION not between", value1, value2, "idSceneRevision");
			return (Criteria) this;
		}

		public Criteria andIdSceneIsNull() {
			addCriterion("ID_SCENE is null");
			return (Criteria) this;
		}

		public Criteria andIdSceneIsNotNull() {
			addCriterion("ID_SCENE is not null");
			return (Criteria) this;
		}

		public Criteria andIdSceneEqualTo(Long value) {
			addCriterion("ID_SCENE =", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotEqualTo(Long value) {
			addCriterion("ID_SCENE <>", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneGreaterThan(Long value) {
			addCriterion("ID_SCENE >", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE >=", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneLessThan(Long value) {
			addCriterion("ID_SCENE <", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneLessThanOrEqualTo(Long value) {
			addCriterion("ID_SCENE <=", value, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneIn(List<Long> values) {
			addCriterion("ID_SCENE in", values, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotIn(List<Long> values) {
			addCriterion("ID_SCENE not in", values, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE between", value1, value2, "idScene");
			return (Criteria) this;
		}

		public Criteria andIdSceneNotBetween(Long value1, Long value2) {
			addCriterion("ID_SCENE not between", value1, value2, "idScene");
			return (Criteria) this;
		}

		public Criteria andSelectedIsNull() {
			addCriterion("SELECTED is null");
			return (Criteria) this;
		}

		public Criteria andSelectedIsNotNull() {
			addCriterion("SELECTED is not null");
			return (Criteria) this;
		}

		public Criteria andSelectedEqualTo(String value) {
			addCriterion("SELECTED =", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotEqualTo(String value) {
			addCriterion("SELECTED <>", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedGreaterThan(String value) {
			addCriterion("SELECTED >", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedGreaterThanOrEqualTo(String value) {
			addCriterion("SELECTED >=", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedLessThan(String value) {
			addCriterion("SELECTED <", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedLessThanOrEqualTo(String value) {
			addCriterion("SELECTED <=", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedLike(String value) {
			addCriterion("SELECTED like", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotLike(String value) {
			addCriterion("SELECTED not like", value, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedIn(List<String> values) {
			addCriterion("SELECTED in", values, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotIn(List<String> values) {
			addCriterion("SELECTED not in", values, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedBetween(String value1, String value2) {
			addCriterion("SELECTED between", value1, value2, "selected");
			return (Criteria) this;
		}

		public Criteria andSelectedNotBetween(String value1, String value2) {
			addCriterion("SELECTED not between", value1, value2, "selected");
			return (Criteria) this;
		}

		public Criteria andScenePositionIsNull() {
			addCriterion("SCENE_POSITION is null");
			return (Criteria) this;
		}

		public Criteria andScenePositionIsNotNull() {
			addCriterion("SCENE_POSITION is not null");
			return (Criteria) this;
		}

		public Criteria andScenePositionEqualTo(Integer value) {
			addCriterion("SCENE_POSITION =", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionNotEqualTo(Integer value) {
			addCriterion("SCENE_POSITION <>", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionGreaterThan(Integer value) {
			addCriterion("SCENE_POSITION >", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("SCENE_POSITION >=", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionLessThan(Integer value) {
			addCriterion("SCENE_POSITION <", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionLessThanOrEqualTo(Integer value) {
			addCriterion("SCENE_POSITION <=", value, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionIn(List<Integer> values) {
			addCriterion("SCENE_POSITION in", values, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionNotIn(List<Integer> values) {
			addCriterion("SCENE_POSITION not in", values, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionBetween(Integer value1, Integer value2) {
			addCriterion("SCENE_POSITION between", value1, value2, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andScenePositionNotBetween(Integer value1, Integer value2) {
			addCriterion("SCENE_POSITION not between", value1, value2, "scenePosition");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionIsNull() {
			addCriterion("SCENE_DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionIsNotNull() {
			addCriterion("SCENE_DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION =", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION <>", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionGreaterThan(String value) {
			addCriterion("SCENE_DESCRIPTION >", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION >=", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionLessThan(String value) {
			addCriterion("SCENE_DESCRIPTION <", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionLessThanOrEqualTo(String value) {
			addCriterion("SCENE_DESCRIPTION <=", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionLike(String value) {
			addCriterion("SCENE_DESCRIPTION like", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotLike(String value) {
			addCriterion("SCENE_DESCRIPTION not like", value, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionIn(List<String> values) {
			addCriterion("SCENE_DESCRIPTION in", values, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotIn(List<String> values) {
			addCriterion("SCENE_DESCRIPTION not in", values, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionBetween(String value1, String value2) {
			addCriterion("SCENE_DESCRIPTION between", value1, value2, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneDescriptionNotBetween(String value1, String value2) {
			addCriterion("SCENE_DESCRIPTION not between", value1, value2, "sceneDescription");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusIsNull() {
			addCriterion("SCENE_TASK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusIsNotNull() {
			addCriterion("SCENE_TASK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusEqualTo(Integer value) {
			addCriterion("SCENE_TASK_STATUS =", value, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusNotEqualTo(Integer value) {
			addCriterion("SCENE_TASK_STATUS <>", value, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusGreaterThan(Integer value) {
			addCriterion("SCENE_TASK_STATUS >", value, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("SCENE_TASK_STATUS >=", value, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusLessThan(Integer value) {
			addCriterion("SCENE_TASK_STATUS <", value, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusLessThanOrEqualTo(Integer value) {
			addCriterion("SCENE_TASK_STATUS <=", value, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusIn(List<Integer> values) {
			addCriterion("SCENE_TASK_STATUS in", values, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusNotIn(List<Integer> values) {
			addCriterion("SCENE_TASK_STATUS not in", values, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusBetween(Integer value1, Integer value2) {
			addCriterion("SCENE_TASK_STATUS between", value1, value2, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andSceneTaskStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("SCENE_TASK_STATUS not between", value1, value2, "sceneTaskStatus");
			return (Criteria) this;
		}

		public Criteria andChapterPositionIsNull() {
			addCriterion("CHAPTER_POSITION is null");
			return (Criteria) this;
		}

		public Criteria andChapterPositionIsNotNull() {
			addCriterion("CHAPTER_POSITION is not null");
			return (Criteria) this;
		}

		public Criteria andChapterPositionEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION =", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionNotEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION <>", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionGreaterThan(Integer value) {
			addCriterion("CHAPTER_POSITION >", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION >=", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionLessThan(Integer value) {
			addCriterion("CHAPTER_POSITION <", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionLessThanOrEqualTo(Integer value) {
			addCriterion("CHAPTER_POSITION <=", value, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionIn(List<Integer> values) {
			addCriterion("CHAPTER_POSITION in", values, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionNotIn(List<Integer> values) {
			addCriterion("CHAPTER_POSITION not in", values, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionBetween(Integer value1, Integer value2) {
			addCriterion("CHAPTER_POSITION between", value1, value2, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterPositionNotBetween(Integer value1, Integer value2) {
			addCriterion("CHAPTER_POSITION not between", value1, value2, "chapterPosition");
			return (Criteria) this;
		}

		public Criteria andChapterTitleIsNull() {
			addCriterion("CHAPTER_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andChapterTitleIsNotNull() {
			addCriterion("CHAPTER_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andChapterTitleEqualTo(String value) {
			addCriterion("CHAPTER_TITLE =", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotEqualTo(String value) {
			addCriterion("CHAPTER_TITLE <>", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleGreaterThan(String value) {
			addCriterion("CHAPTER_TITLE >", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleGreaterThanOrEqualTo(String value) {
			addCriterion("CHAPTER_TITLE >=", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleLessThan(String value) {
			addCriterion("CHAPTER_TITLE <", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleLessThanOrEqualTo(String value) {
			addCriterion("CHAPTER_TITLE <=", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleLike(String value) {
			addCriterion("CHAPTER_TITLE like", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotLike(String value) {
			addCriterion("CHAPTER_TITLE not like", value, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleIn(List<String> values) {
			addCriterion("CHAPTER_TITLE in", values, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotIn(List<String> values) {
			addCriterion("CHAPTER_TITLE not in", values, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleBetween(String value1, String value2) {
			addCriterion("CHAPTER_TITLE between", value1, value2, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andChapterTitleNotBetween(String value1, String value2) {
			addCriterion("CHAPTER_TITLE not between", value1, value2, "chapterTitle");
			return (Criteria) this;
		}

		public Criteria andIdChapterIsNull() {
			addCriterion("ID_CHAPTER is null");
			return (Criteria) this;
		}

		public Criteria andIdChapterIsNotNull() {
			addCriterion("ID_CHAPTER is not null");
			return (Criteria) this;
		}

		public Criteria andIdChapterEqualTo(Long value) {
			addCriterion("ID_CHAPTER =", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterNotEqualTo(Long value) {
			addCriterion("ID_CHAPTER <>", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterGreaterThan(Long value) {
			addCriterion("ID_CHAPTER >", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_CHAPTER >=", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterLessThan(Long value) {
			addCriterion("ID_CHAPTER <", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterLessThanOrEqualTo(Long value) {
			addCriterion("ID_CHAPTER <=", value, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterIn(List<Long> values) {
			addCriterion("ID_CHAPTER in", values, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterNotIn(List<Long> values) {
			addCriterion("ID_CHAPTER not in", values, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterBetween(Long value1, Long value2) {
			addCriterion("ID_CHAPTER between", value1, value2, "idChapter");
			return (Criteria) this;
		}

		public Criteria andIdChapterNotBetween(Long value1, Long value2) {
			addCriterion("ID_CHAPTER not between", value1, value2, "idChapter");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
	 * @mbggenerated  Sat Jul 05 08:57:49 CEST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.V_SELECTED_SCENE_REVISIONS
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 23 23:39:01 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}